{--- 0-9 ---}
      ( Extension: '.123';         MimeType: 'application/vnd.lotus-1-2-3'                                             ), // 2025.03.14 [IANA: Lotus 1-2-3]
      ( Extension: '.323';         MimeType: 'text/h323'                                                               ), // Indy 10.6.3.2
      ( Extension: '.3dml';        MimeType: 'text/vnd.in3d.3dml'                                                      ), // 2025.03.14 [IANA: In3D]
      ( Extension: '.3g2';         MimeType: 'video/3gpp2'                                                             ), // 2025.03.14 [Wikipedia: 3G2]
      ( Extension: '.3gp';         MimeType: 'video/3gpp'                                                              ), // 2025.03.14 [Wikipedia: 3GP]
      ( Extension: '.7z';          MimeType: 'application/x-7z-compressed'                                             ), // 2025.03.14 [Wikipedia: 7-Zip]

{--- A ---}
      ( Extension: '.a';           MimeType: 'application/x-archive'                                                   ), // Indy 10.6.3.2
      ( Extension: '.aab';         MimeType: 'application/x-authorware-bin'                                            ), // 2025.03.14 [Wikipedia: Authorware]
      ( Extension: '.aac';         MimeType: 'audio/mp4'                                                               ), // Indy 10.6.3.2
      ( Extension: '.aac';         MimeType: 'audio/aac'                                                               ), // 2025.11.30 Gemini AI
      ( Extension: '.aac';         MimeType: 'audio/x-aac'                                                             ), // 2025.03.14 [Wikipedia: AAC]
      ( Extension: '.aam';         MimeType: 'application/x-authorware-map'                                            ), // 2025.03.14 [Wikipedia: Authorware]
      ( Extension: '.aas';         MimeType: 'application/x-authorware-seg'                                            ), // 2025.03.14 [Wikipedia: Authorware]
      ( Extension: '.abw';         MimeType: 'application/x-abiword'                                                   ), // 2025.03.14 [Wikipedia: AbiWord]
      ( Extension: '.ac';          MimeType: 'application/pkix-attr-cert'                                              ), // 2025.03.14 [RFC 5877]
      ( Extension: '.ac3';         MimeType: 'audio/ac3'                                                               ), // 2025.11.30 Gemini AI
      ( Extension: '.acc';         MimeType: 'application/vnd.americandynamics.acc'                                    ), // 2025.03.14 [IANA: Active Content Compression]
      ( Extension: '.ace';         MimeType: 'application/x-ace-compressed'                                            ), // 2025.03.14 [Wikipedia: ACE]
      ( Extension: '.acu';         MimeType: 'application/vnd.acucobol'                                                ), // 2025.03.14 [IANA: ACU Cobol]
      ( Extension: '.adp';         MimeType: 'audio/adpcm'                                                             ), // 2025.03.14 [Wikipedia: ADPCM]
      ( Extension: '.aep';         MimeType: 'application/vnd.audiograph'                                              ), // 2025.03.14 [IANA: Audiograph]
      ( Extension: '.afp';         MimeType: 'application/vnd.ibm.modcap'                                              ), // 2025.03.14 [IANA: MO:DCA-P]
      ( Extension: '.ahead';       MimeType: 'application/vnd.ahead.space'                                             ), // 2025.03.14 [IANA: Ahead AIR Application]
      ( Extension: '.ai';          MimeType: 'application/postscript'                                                  ), // 2025.03.14 [Wikipedia: PostScript]
      ( Extension: '.aif';         MimeType: 'audio/x-aiff'                                                            ), // 2025.03.14 [Wikipedia: Audio Interchange File Format]
      ( Extension: '.aifc';        MimeType: 'audio/x-aiff'                                                            ), // Indy 10.6.3.2
      ( Extension: '.aiff';        MimeType: 'audio/x-aiff'                                                            ), // Indy 10.6.3.2
      ( Extension: '.air';         MimeType: 'application/vnd.adobe.air-application-installer-package+zip'             ), // 2025.03.14 [Building AIR Applications]
      ( Extension: '.ait';         MimeType: 'application/vnd.dvb.ait'                                                 ), // 2025.03.14 [IANA: Digital Video Broadcasting]
      ( Extension: '.alz';         MimeType: 'application/x-alz-compressed'                                            ), // Indy 10.6.3.2
      ( Extension: '.ami';         MimeType: 'application/vnd.amiga.ami'                                               ), // 2025.03.14 [IANA: Amiga]
      ( Extension: '.amr';         MimeType: 'audio/amr'                                                               ), // 2025.11.30 Gemini AI
      ( Extension: '.ani';         MimeType: 'application/x-navi-animation'                                            ), // Indy 10.6.3.2
      ( Extension: '.apk';         MimeType: 'application/vnd.android.package-archive'                                 ), // 2025.03.14 [Wikipedia: APK File Format]
      ( Extension: '.apng';        MimeType: 'image/apng'                                                              ), // 2025.11.30 Gemini AI
      ( Extension: '.application'; MimeType: 'application/x-ms-application'                                            ), // 2025.03.14 [Wikipedia: ClickOnce]
      ( Extension: '.apr';         MimeType: 'application/vnd.lotus-approach'                                          ), // 2025.03.14 [IANA: Lotus Approach]
      ( Extension: '.arc';         MimeType: 'application/x-freearc'                                                   ), // 2025.03.14 [FreeArc]
      ( Extension: '.arj';         MimeType: 'application/x-arj'                                                       ), // Indy 10.6.3.2
      ( Extension: '.art';         MimeType: 'image/x-jg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.asc';         MimeType: 'text/plain'                                                              ), // 2025.11.30 Gemini AI
      ( Extension: '.asf';         MimeType: 'video/x-ms-asf'                                                          ), // Indy 10.6.3.2
      ( Extension: '.asf';         MimeType: 'application/vnd.ms-asf'                                                  ), // Indy 10.6.3.2
      ( Extension: '.asf';         MimeType: 'video/x-ms-asf'                                                          ), // 2025.03.14 [Wikipedia: Advanced Systems Format (ASF)]
      ( Extension: '.asm';         MimeType: 'text/x-asm'                                                              ), // Indy 10.6.3.2
      ( Extension: '.aso';         MimeType: 'application/vnd.accpac.simply.aso'                                       ), // 2025.03.14 [IANA: Simply Accounting]
      ( Extension: '.asx';         MimeType: 'video/x-ms-asf'                                                          ), // Indy 10.6.3.2
      ( Extension: '.asx';         MimeType: 'video/x-ms-asf-plugin'                                                   ), // Indy 10.6.3.2
      ( Extension: '.atc';         MimeType: 'application/vnd.acucorp'                                                 ), // 2025.03.14 [IANA: ACU Cobol]
      ( Extension: '.atom, .xml';  MimeType: 'application/atom+xml'                                                    ), // 2025.03.14 [RFC 4287]
      ( Extension: '.atomcat';     MimeType: 'application/atomcat+xml'                                                 ), // 2025.03.14 [RFC 5023]
      ( Extension: '.atomsvc';     MimeType: 'application/atomsvc+xml'                                                 ), // 2025.03.14 [RFC 5023]
      ( Extension: '.atx';         MimeType: 'application/vnd.antix.game-component'                                    ), // 2025.03.14 [IANA: Antix Game Component]
      ( Extension: '.au';          MimeType: 'audio/basic'                                                             ), // 2025.03.14 [Wikipedia: Sun audio]
      ( Extension: '.avi';         MimeType: 'video/x-msvideo'                                                         ), // 2025.03.14 [Wikipedia: AVI]
      ( Extension: '.avif';        MimeType: 'image/avif'                                                              ), // 2025.03.14 [AV1 Image File Format]
      ( Extension: '.aw';          MimeType: 'application/applixware'                                                  ), // 2025.03.14 [Vistasource]
      ( Extension: '.awb';         MimeType: 'audio/amr-wb'                                                            ), // 2025.11.30 Gemini AI
      ( Extension: '.azf';         MimeType: 'application/vnd.airzip.filesecure.azf'                                   ), // 2025.03.14 [IANA: AirZip]
      ( Extension: '.azs';         MimeType: 'application/vnd.airzip.filesecure.azs'                                   ), // 2025.03.14 [IANA: AirZip]
      ( Extension: '.azw';         MimeType: 'application/vnd.amazon.ebook'                                            ), // 2025.03.14 [Kindle Direct Publishing]

{--- B ---}
      ( Extension: '.bas';         MimeType: 'text/plain'                                                              ),  // 2025.11.30 Gemini AI
      ( Extension: '.bat';         MimeType: 'application/x-msdos-program'                                             ), // Indy 10.6.3.2
      ( Extension: '.bcpio';       MimeType: 'application/x-bcpio'                                                     ), // 2025.03.14 [Wikipedia: cpio]
      ( Extension: '.bdf';         MimeType: 'application/x-font-bdf'                                                  ), // 2025.03.14 [Wikipedia: Glyph Bitmap Distribution Format]
      ( Extension: '.bdm';         MimeType: 'application/vnd.syncml.dm+wbxml'                                         ), // 2025.03.14 [IANA: SyncML]
      ( Extension: '.bed';         MimeType: 'application/vnd.realvnc.bed'                                             ), // 2025.03.14 [IANA: RealVNC]
      ( Extension: '.bh2';         MimeType: 'application/vnd.fujitsu.oasysprs'                                        ), // 2025.03.14 [IANA: Fujitsu Oasys]
      ( Extension: '.bin';         MimeType: 'application/octet-stream'                                                ), // 2025.03.14
      ( Extension: '.bmi';         MimeType: 'application/vnd.bmi'                                                     ), // 2025.03.14 [IANA: BMI]
      ( Extension: '.bmp';         MimeType: 'image/bmp'                                                               ), // 2025.03.14 [Wikipedia: BMP File Format]
      ( Extension: '.box';         MimeType: 'application/vnd.previewsystems.box'                                      ), // 2025.03.14 [IANA: Preview Systems ZipLock/Vbox]
      ( Extension: '.boz';         MimeType: 'application/x-bzip2'                                                     ), // Indy 10.6.3.2
      ( Extension: '.btif';        MimeType: 'image/prs.btif'                                                          ), // 2025.03.14 [IANA: BTIF]
      ( Extension: '.bz';          MimeType: 'application/x-bzip'                                                      ), // 2025.03.14 [Wikipedia: Bzip]
      ( Extension: '.bz2';         MimeType: 'application/x-bzip2'                                                     ), // 2025.03.14 [Wikipedia: Bzip]

{--- C ---}
      ( Extension: '.c';           MimeType: 'text/x-csrc'                                                             ), // Indy 10.6.3.2
      ( Extension: '.c';           MimeType: 'text/x-c'                                                                ), // 2025.03.14 [Wikipedia: C Programming Language]
      ( Extension: '.c++';         MimeType: 'text/x-c++src'                                                           ), // Indy 10.6.3.2
      ( Extension: '.c11amc';      MimeType: 'application/vnd.cluetrust.cartomobile-config'                            ), // 2025.03.14 [IANA: CartoMobile]
      ( Extension: '.c11amz';      MimeType: 'application/vnd.cluetrust.cartomobile-config-pkg'                        ), // 2025.03.14 [IANA: CartoMobile]
      ( Extension: '.c4g';         MimeType: 'application/vnd.clonk.c4group'                                           ), // 2025.03.14 [IANA: Clonk]
      ( Extension: '.cab';         MimeType: 'application/vnd.ms-cab-compressed'                                       ), // 2025.03.14 [IANA: MS Cabinet File]
      ( Extension: '.caf';         MimeType: 'audio/x-caf'                                                             ), // 2025.11.30 Gemini AI
      ( Extension: '.cal';         MimeType: 'image/x-cals'                                                            ), // 2025.11.30 Gemini AI
      ( Extension: '.car';         MimeType: 'application/vnd.curl.car'                                                ), // 2025.03.14 [IANA: CURL Applet]
      ( Extension: '.cat';         MimeType: 'application/vnd.ms-pki.seccat'                                           ), // 2025.03.14 [IANA: MS Trust UI Provider]
      ( Extension: '.cc';          MimeType: 'text/x-c++src'                                                           ), // Indy 10.6.3.2
      ( Extension: '.ccn';         MimeType: 'application/x-cnc'                                                       ), // Indy 10.6.3.2
      ( Extension: '.cco';         MimeType: 'application/x-cocoa'                                                     ), // Indy 10.6.3.2
      ( Extension: '.ccxml';       MimeType: 'application/ccxml+xml,'                                                  ), // 2025.03.14 [Voice Browser Call Control: CCXML Version 1.0]
      ( Extension: '.cda';         MimeType: 'application/x-cdf'                                                       ), // 2025.03.14 [Wikipedia: CDA File]
      ( Extension: '.cdbcmsg';     MimeType: 'application/vnd.contact.cmsg'                                            ), // 2025.03.14 [IANA: CIM Database]
      ( Extension: '.cdf';         MimeType: 'application/x-cdf'                                                       ), // Indy 10.6.3.2
      ( Extension: '.cdkey';       MimeType: 'application/vnd.mediastation.cdkey'                                      ), // 2025.03.14 [IANA: MediaRemote]
      ( Extension: '.cdmia';       MimeType: 'application/cdmi-capability'                                             ), // 2025.03.14 [RFC 6208]
      ( Extension: '.cdmic';       MimeType: 'application/cdmi-container'                                              ), // 2025.03.14 [RFC 6209]
      ( Extension: '.cdmid';       MimeType: 'application/cdmi-domain'                                                 ), // 2025.03.14 [RFC 6210]
      ( Extension: '.cdmio';       MimeType: 'application/cdmi-object'                                                 ), // 2025.03.14 [RFC 6211]
      ( Extension: '.cdmiq';       MimeType: 'application/cdmi-queue'                                                  ), // 2025.03.14 [RFC 6212]
      ( Extension: '.cdr';         MimeType: 'image/x-coreldraw'                                                       ), // Indy 10.6.3.2
      ( Extension: '.cdt';         MimeType: 'image/x-coreldrawtemplate'                                               ), // Indy 10.6.3.2
      ( Extension: '.cdx';         MimeType: 'chemical/x-cdx'                                                          ), // 2025.03.14 [ChemDraw eXchange file]
      ( Extension: '.cdxml';       MimeType: 'application/vnd.chemdraw+xml'                                            ), // 2025.03.14 [IANA: Chem Draw]
      ( Extension: '.cdy';         MimeType: 'application/vnd.cinderella'                                              ), // 2025.03.14 [IANA: Cinderella]
      ( Extension: '.cer';         MimeType: 'application/x-x509-ca-cert'                                              ), // Indy 10.6.3.2
      ( Extension: '.cer';         MimeType: 'application/pkix-cert'                                                   ), // 2025.03.14 [RFC 2585]
      ( Extension: '.cgm';         MimeType: 'image/cgm'                                                               ), // 2025.03.14 [Wikipedia: Computer Graphics Metafile]
      ( Extension: '.chat';        MimeType: 'application/x-chat'                                                      ), // 2025.03.14 [Wikipedia: pIRCh]
      ( Extension: '.chm';         MimeType: 'application/vnd.ms-htmlhelp'                                             ), // 2025.03.14 [IANA:MS Html Help File]
      ( Extension: '.chrt';        MimeType: 'application/vnd.kde.kchart'                                              ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.cif';         MimeType: 'chemical/x-cif'                                                          ), // 2025.03.14 [Crystallographic Interchange Format]
      ( Extension: '.cii';         MimeType: 'application/vnd.anser-web-certificate-issue-initiation'                  ), // 2025.03.14 [IANA: ANSWER-WEB]
      ( Extension: '.cil';         MimeType: 'application/vnd.ms-artgalry'                                             ), // 2025.03.14 [IANA: MS Artgalry]
      ( Extension: '.cla';         MimeType: 'application/vnd.claymore'                                                ), // 2025.03.14 [IANA: Claymore]
      ( Extension: '.class';       MimeType: 'application/java-vm'                                                     ), // 2025.03.14 [Wikipedia: Java Bytecode]
      ( Extension: '.clkk';        MimeType: 'application/vnd.crick.clicker.keyboard'                                  ), // 2025.03.14 [IANA: Clicker]
      ( Extension: '.clkp';        MimeType: 'application/vnd.crick.clicker.palette'                                   ), // 2025.03.14 [IANA: Clicker]
      ( Extension: '.clkt';        MimeType: 'application/vnd.crick.clicker.template'                                  ), // 2025.03.14 [IANA: Clicker]
      ( Extension: '.clkw';        MimeType: 'application/vnd.crick.clicker.wordbank'                                  ), // 2025.03.14 [IANA: Clicker]
      ( Extension: '.clkx';        MimeType: 'application/vnd.crick.clicker'                                           ), // 2025.03.14 [IANA: Clicker]
      ( Extension: '.clp';         MimeType: 'application/x-msclip'                                                    ), // 2025.03.14 [Wikipedia: Clipboard]
      ( Extension: '.cmc';         MimeType: 'application/vnd.cosmocaller'                                             ), // 2025.03.14 [IANA: CosmoCaller]
      ( Extension: '.cmd';         MimeType: 'text/plain'                                                              ), // 2025.11.30 Gemini AI
      ( Extension: '.cmdf';        MimeType: 'chemical/x-cmdf'                                                         ), // 2025.03.14 [CrystalMaker Data Format]
      ( Extension: '.cml';         MimeType: 'chemical/x-cml'                                                          ), // 2025.03.14 [Wikipedia: Chemical Markup Language]
      ( Extension: '.cmp';         MimeType: 'application/vnd.yellowriver-custom-menu'                                 ), // 2025.03.14 [IANA: CustomMenu]
      ( Extension: '.cmx';         MimeType: 'image/x-cmx'                                                             ), // 2025.03.14 [Wikipedia: CorelDRAW]
      ( Extension: '.cod';         MimeType: 'application/vnd.rim.cod'                                                 ), // 2025.03.14
      ( Extension: '.com';         MimeType: 'application/x-msdos-program'                                             ), // Indy 10.6.3.2
      ( Extension: '.conf';        MimeType: 'text/plain'                                                              ), // 2025.11.30 Gemini AI
      ( Extension: '.cpio';        MimeType: 'application/x-cpio'                                                      ), // 2025.03.14 [Wikipedia: cpio]
      ( Extension: '.cpp';         MimeType: 'text/x-c++src'                                                           ), // Indy 10.6.3.2
      ( Extension: '.cpt';         MimeType: 'image/x-corelphotopaint'                                                 ), // Indy 10.6.3.2
      ( Extension: '.cpt';         MimeType: 'application/mac-compactpro'                                              ), // 2025.03.14 [Compact Pro]
      ( Extension: '.cqk';         MimeType: 'application/x-calquick'                                                  ), // Indy 10.6.3.2
      ( Extension: '.crd';         MimeType: 'application/x-mscardfile'                                                ), // 2025.03.14 [Wikipedia: Information Card]
      ( Extension: '.crl';         MimeType: 'application/pkix-crl'                                                    ), // 2025.03.14 [RFC 2585]
      ( Extension: '.crt';         MimeType: 'application/x-x509-ca-cert'                                              ), // 2025.11.30 Gemini AI
      ( Extension: '.cryptonote';  MimeType: 'application/vnd.rig.cryptonote'                                          ), // 2025.03.14 [IANA: CryptoNote]
      ( Extension: '.cs';          MimeType: 'text/x-csharp'                                                           ), // Indy 10.6.3.2
      ( Extension: '.csh';         MimeType: 'application/x-csh'                                                       ), // 2025.03.14 [Wikipedia: C Shell]
      ( Extension: '.csml';        MimeType: 'chemical/x-csml'                                                         ), // 2025.03.14 [Wikipedia: Chemical Style Markup Language]
      ( Extension: '.csp';         MimeType: 'application/vnd.commonspace'                                             ), // 2025.03.14 [IANA: CommonSpace]
      ( Extension: '.css';         MimeType: 'text/css'                                                                ), // 2025.03.14 [Wikipedia: CSS]
      ( Extension: '.csv';         MimeType: 'text/csv'                                                                ), // 2025.03.14 [Wikipedia: CSV]
      ( Extension: '.cu';          MimeType: 'application/cu-seeme'                                                    ), // 2025.03.14 [White Pine]
      ( Extension: '.curl';        MimeType: 'text/vnd.curl'                                                           ), // 2025.03.14 [Curl Applet]
      ( Extension: '.cww';         MimeType: 'application/prs.cww'                                                     ), // 2025.03.14
      ( Extension: '.cxx';         MimeType: 'text/x-c++src'                                                           ), // Indy 10.6.3.2

      ( Extension: '.dae';         MimeType: 'model/vnd.collada+xml'                                                   ), // 2025.03.14 [IANA: COLLADA]
      ( Extension: '.daf';         MimeType: 'application/vnd.mobius.daf'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.dar';         MimeType: 'application/x-dar'                                                       ), // Indy 10.6.3.2
      ( Extension: '.davmount';    MimeType: 'application/davmount+xml'                                                ), // 2025.03.14 [RFC 4918]
      ( Extension: '.dbf';         MimeType: 'application/x-dbase'                                                     ), // Indy 10.6.3.2
      ( Extension: '.dcr';         MimeType: 'application/x-director'                                                  ), // Indy 10.6.3.2
      ( Extension: '.dcurl';       MimeType: 'text/vnd.curl.dcurl'                                                     ), // 2025.03.14 [Curl Detached Applet]
      ( Extension: '.dd2';         MimeType: 'application/vnd.oma.dd2+xml'                                             ), // 2025.03.14 [IANA: OMA Download Agents]
      ( Extension: '.ddd';         MimeType: 'application/vnd.fujixerox.ddd'                                           ), // 2025.03.14 [IANA: Fujitsu DDD]
      ( Extension: '.deb';         MimeType: 'application/x-debian-package'                                            ), // 2025.03.14 [Wikipedia: Debian Package]
      ( Extension: '.der';         MimeType: 'application/x-x509-ca-cert'                                              ), // 2025.03.14 [Wikipedia: X.509]
      ( Extension: '.dfac';        MimeType: 'application/vnd.dreamfactory'                                            ), // 2025.03.14 [IANA: DreamFactory]
      ( Extension: '.dir';         MimeType: 'application/x-director'                                                  ), // 2025.03.14 [Wikipedia: Adobe Shockwave Player]
      ( Extension: '.dis';         MimeType: 'application/vnd.mobius.dis'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.dist';        MimeType: 'vnd.apple.installer+xml'                                                 ), // Indy 10.6.3.2
      ( Extension: '.distz';       MimeType: 'vnd.apple.installer+xml'                                                 ), // Indy 10.6.3.2
      ( Extension: '.djv';         MimeType: 'image/vnd.djvu'                                                          ), // Indy 10.6.3.2
      ( Extension: '.djvu';        MimeType: 'image/vnd.djvu'                                                          ), // 2025.03.14 [Wikipedia: DjVu]
      ( Extension: '.dl';          MimeType: 'video/dl'                                                                ), // Indy 10.6.3.2
      ( Extension: '.dll';         MimeType: 'application/x-msdos-program'                                             ), // Indy 10.6.3.2
      ( Extension: '.dmg';         MimeType: 'application/x-apple-diskimage'                                           ), // 2025.03.14 [Apple Disk Image]
      ( Extension: '.dna';         MimeType: 'application/vnd.dna'                                                     ), // 2025.03.14 [IANA: New Moon Liftoff/DNA]
      ( Extension: '.doc';         MimeType: 'application/msword'                                                      ), // 2025.03.14 [Wikipedia: Microsoft Word]
      ( Extension: '.docm';        MimeType: 'application/vnd.ms-word.document.macroenabled.12'                        ), // 2025.03.14 [IANA: MS Word]
      ( Extension: '.docx';        MimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ), // 2025.03.14 [IANA: OOXML - Word Document]
      ( Extension: '.dot';         MimeType: 'application/msword'                                                      ), // Indy 10.6.3.2
      ( Extension: '.dotm';        MimeType: 'application/vnd.ms-word.template.macroenabled.12'                        ), // 2025.03.14 [IANA: MS Word]
      ( Extension: '.dotx';        MimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template' ), // 2025.03.14 [IANA: OOXML - Word Document Template]
      ( Extension: '.dp';          MimeType: 'application/vnd.osgi.dp'                                                 ), // 2025.03.14 [IANA: OSGi Deployment Package]
      ( Extension: '.dpg';         MimeType: 'application/vnd.dpgraph'                                                 ), // 2025.03.14 [IANA: DPGraph]
      ( Extension: '.dra';         MimeType: 'audio/vnd.dra'                                                           ), // 2025.03.14 [IANA: DRA]
      ( Extension: '.dsc';         MimeType: 'text/prs.lines.tag'                                                      ), // 2025.03.14 [IANA: PRS Lines Tag]
      ( Extension: '.dssc';        MimeType: 'application/dssc+der'                                                    ), // 2025.03.14 [RFC 5698]
      ( Extension: '.dtb';         MimeType: 'application/x-dtbook+xml'                                                ), // 2025.03.14 [Wikipedia: EPUB]
      ( Extension: '.dtd';         MimeType: 'application/xml-dtd'                                                     ), // 2025.03.14 [W3C DTD]
      ( Extension: '.dts';         MimeType: 'audio/vnd.dts'                                                           ), // 2025.03.14 [IANA: DTS]
      ( Extension: '.dtshd';       MimeType: 'audio/vnd.dts.hd'                                                        ), // 2025.03.14 [IANA: DTS HD]
      ( Extension: '.dv';          MimeType: 'video/dv'                                                                ), // Indy 10.6.3.2
      ( Extension: '.dvi';         MimeType: 'application/x-dvi'                                                       ), // 2025.03.14 [Wikipedia: DVI]
      ( Extension: '.dwf';         MimeType: 'model/vnd.dwf'                                                           ), // 2025.03.14 [Wikipedia: Design Web Format]
      ( Extension: '.dwg';         MimeType: 'image/vnd.dwg'                                                           ), // 2025.03.14 [Wikipedia: DWG]
      ( Extension: '.dxf';         MimeType: 'image/vnd.dxf'                                                           ), // 2025.03.14 [Wikipedia: AutoCAD DXF]
      ( Extension: '.dxp';         MimeType: 'application/vnd.spotfire.dxp'                                            ), // 2025.03.14 [IANA: TIBCO Spotfire]
      ( Extension: '.dxr';         MimeType: 'application/x-director'                                                  ), // Indy 10.6.3.2
      ( Extension: '.ebk';         MimeType: 'application/x-expandedbook'                                              ), // Indy 10.6.3.2
      ( Extension: '.ecelp4800';   MimeType: 'audio/vnd.nuera.ecelp4800'                                               ), // 2025.03.14 [IANA: ECELP 4800]
      ( Extension: '.ecelp7470';   MimeType: 'audio/vnd.nuera.ecelp7470'                                               ), // 2025.03.14 [IANA: ECELP 7470]
      ( Extension: '.ecelp9600';   MimeType: 'audio/vnd.nuera.ecelp9600'                                               ), // 2025.03.14 [IANA: ECELP 9600]
      ( Extension: '.edm';         MimeType: 'application/vnd.novadigm.edm'                                            ), // 2025.03.14 [IANA: Novadigm's RADIA and EDM products]
      ( Extension: '.edx';         MimeType: 'application/vnd.novadigm.edx'                                            ), // 2025.03.14 [IANA: Novadigm's RADIA and EDM products]
      ( Extension: '.efif';        MimeType: 'application/vnd.picsel'                                                  ), // 2025.03.14 [IANA: Picsel eFIF File]
      ( Extension: '.ei6';         MimeType: 'application/vnd.pg.osasli'                                               ), // 2025.03.14 [IANA: Proprietary P&G Standard Reporting System]
      ( Extension: '.eml';         MimeType: 'message/rfc822'                                                          ), // 2025.03.14 [RFC 2822]
      ( Extension: '.emma';        MimeType: 'application/emma+xml'                                                    ), // 2025.03.14 [EMMA: Extensible MultiModal Annotation markup language]
      ( Extension: '.eol';         MimeType: 'audio/vnd.digital-winds'                                                 ), // 2025.03.14 [IANA: Digital Winds]
      ( Extension: '.eot';         MimeType: 'application/vnd.ms-fontobject'                                           ), // 2025.03.14 [IANA: MS Embedded OpenType]
      ( Extension: '.eps';         MimeType: 'application/postscript'                                                  ), // Indy 10.6.3.2
      ( Extension: '.epub';        MimeType: 'application/epub+zip'                                                    ), // 2025.03.14 [Wikipedia: EPUB]
      ( Extension: '.es';          MimeType: 'application/ecmascript'                                                  ), // 2025.03.14 [ECMA-357]
      ( Extension: '.es3';         MimeType: 'application/vnd.eszigno3+xml'                                            ), // 2025.03.14 [IANA: MICROSEC e-Szign]
      ( Extension: '.esf';         MimeType: 'application/vnd.epson.esf'                                               ), // 2025.03.14 [IANA: QUASS Stream Player]
      ( Extension: '.etx';         MimeType: 'text/x-setext'                                                           ), // 2025.03.14 [Wikipedia: Setext]
      ( Extension: '.evy';         MimeType: 'application/envoy'                                                       ), // Indy 10.6.3.2
      ( Extension: '.exe';         MimeType: 'application/x-msdos-program'                                             ), // Indy 10.6.3.2
      ( Extension: '.exe';         MimeType: 'application/x-msdownload'                                                ), // 2025.03.14 [Wikipedia: EXE]
      ( Extension: '.exi';         MimeType: 'application/exi'                                                         ), // 2025.03.14 [Efficient XML Interchange (EXI) Best Practices]
      ( Extension: '.ext';         MimeType: 'application/vnd.novadigm.ext'                                            ), // 2025.03.14 [IANA: Novadigm's RADIA and EDM products]
      ( Extension: '.ez2';         MimeType: 'application/vnd.ezpix-album'                                             ), // 2025.03.14 [IANA: EZPix Secure Photo Album]
      ( Extension: '.ez3';         MimeType: 'application/vnd.ezpix-package'                                           ), // 2025.03.14 [IANA: EZPix Secure Photo Album]
      ( Extension: '.f';           MimeType: 'text/x-fortran'                                                          ), // 2025.03.14 [Wikipedia: Fortran]
      ( Extension: '.f4v';         MimeType: 'video/x-f4v'                                                             ), // 2025.03.14 [Wikipedia: Flash Video]
      ( Extension: '.fbs';         MimeType: 'image/vnd.fastbidsheet'                                                  ), // 2025.03.14 [IANA: FastBid Sheet]
      ( Extension: '.fcs';         MimeType: 'application/vnd.isac.fcs'                                                ), // 2025.03.14 [IANA: International Society for Advancement of Cytometry]
      ( Extension: '.fdf';         MimeType: 'application/vnd.fdf'                                                     ), // 2025.03.14 [IANA: Forms Data Format]
      ( Extension: '.fe_launch';   MimeType: 'application/vnd.denovo.fcselayout-link'                                  ), // 2025.03.14 [IANA: FCS Express Layout Link]
      ( Extension: '.fg5';         MimeType: 'application/vnd.fujitsu.oasysgp'                                         ), // 2025.03.14 [IANA: Fujitsu Oasys]
      ( Extension: '.fh';          MimeType: 'image/x-freehand'                                                        ), // 2025.03.14 [Wikipedia: Macromedia Freehand]
      ( Extension: '.fif';         MimeType: 'application/fractals'                                                    ), // Indy 10.6.3.2
      ( Extension: '.fig';         MimeType: 'application/x-xfig'                                                      ), // 2025.03.14 [Wikipedia: Xfig]
      ( Extension: '.flc';         MimeType: 'video/flc'                                                               ), // Indy 10.6.3.2
      ( Extension: '.fli';         MimeType: 'video/fli'                                                               ), // Indy 10.6.3.2
      ( Extension: '.fli';         MimeType: 'video/x-fli'                                                             ), // 2025.03.14 [FLI/FLC Animation Format]
      ( Extension: '.flm';         MimeType: 'application/vnd.kde.kivio'                                               ), // Indy 10.6.3.2
      ( Extension: '.flo';         MimeType: 'application/vnd.micrografx.flo'                                          ), // 2025.03.14 [IANA: Micrografx]
      ( Extension: '.flv';         MimeType: 'video/x-flv'                                                             ), // 2025.03.14 [Wikipedia: Flash Video]
      ( Extension: '.flw';         MimeType: 'application/vnd.kde.kivio'                                               ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.flx';         MimeType: 'text/vnd.fmi.flexstor'                                                   ), // 2025.03.14 [IANA: FLEXSTOR]
      ( Extension: '.fly';         MimeType: 'text/vnd.fly'                                                            ), // 2025.03.14 [IANA: Fly]
      ( Extension: '.fm';          MimeType: 'application/vnd.framemaker'                                              ), // 2025.03.14 [IANA: FrameMaker]
      ( Extension: '.fml';         MimeType: 'application/x-file-mirror-list'                                          ), // Indy 10.6.3.2
      ( Extension: '.fnc';         MimeType: 'application/vnd.frogans.fnc'                                             ), // 2025.03.14 [IANA: Frogans Player]
      ( Extension: '.fpx';         MimeType: 'image/vnd.fpx'                                                           ), // 2025.03.14 [IANA: FPX]
      ( Extension: '.fsc';         MimeType: 'application/vnd.fsc.weblaunch'                                           ), // 2025.03.14 [IANA: Friendly Software Corporation]
      ( Extension: '.fst';         MimeType: 'image/vnd.fst'                                                           ), // 2025.03.14 [IANA: FAST Search & Transfer ASA]
      ( Extension: '.ftc';         MimeType: 'application/vnd.fluxtime.clip'                                           ), // 2025.03.14 [IANA: FluxTime Clip]
      ( Extension: '.fti';         MimeType: 'application/vnd.anser-web-funds-transfer-initiation'                     ), // 2025.03.14 [IANA: ANSWER-WEB]
      ( Extension: '.fvt';         MimeType: 'video/vnd.fvt'                                                           ), // 2025.03.14 [IANA: FVT]
      ( Extension: '.fxp';         MimeType: 'application/vnd.adobe.fxp'                                               ), // 2025.03.14 [IANA: Adobe Flex Project]
      ( Extension: '.fzs';         MimeType: 'application/vnd.fuzzysheet'                                              ), // 2025.03.14 [IANA: FuzySheet]
      ( Extension: '.g2w';         MimeType: 'application/vnd.geoplan'                                                 ), // 2025.03.14 [IANA: GeoplanW]
      ( Extension: '.g3';          MimeType: 'image/g3fax'                                                             ), // 2025.03.14 [Wikipedia: G3 Fax Image]
      ( Extension: '.g3w';         MimeType: 'application/vnd.geospace'                                                ), // 2025.03.14 [IANA: GeospacW]
      ( Extension: '.gac';         MimeType: 'application/vnd.groove-account'                                          ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.gdl';         MimeType: 'model/vnd.gdl'                                                           ), // 2025.03.14 [IANA: GDL]
      ( Extension: '.geo';         MimeType: 'application/vnd.dynageo'                                                 ), // 2025.03.14 [IANA: DynaGeo]
      ( Extension: '.gex';         MimeType: 'application/vnd.geometry-explorer'                                       ), // 2025.03.14 [IANA: GeoMetry Explorer]
      ( Extension: '.ggb';         MimeType: 'application/vnd.geogebra.file'                                           ), // 2025.03.14 [IANA: GeoGebra]
      ( Extension: '.ggt';         MimeType: 'application/vnd.geogebra.tool'                                           ), // 2025.03.14 [IANA: GeoGebra]
      ( Extension: '.ghf';         MimeType: 'application/vnd.groove-help'                                             ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.gif';         MimeType: 'image/gif'                                                               ), // 2025.03.14 [Wikipedia: Graphics Interchange Format]
      ( Extension: '.gim';         MimeType: 'application/vnd.groove-identity-message'                                 ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.gl';          MimeType: 'video/gl'                                                                ), // Indy 10.6.3.2
      ( Extension: '.gmx';         MimeType: 'application/vnd.gmx'                                                     ), // 2025.03.14 [IANA: GameMaker ActiveX]
      ( Extension: '.gnumeric';    MimeType: 'application/x-gnumeric'                                                  ), // 2025.03.14 [Wikipedia: Gnumeric]
      ( Extension: '.gph';         MimeType: 'application/vnd.flographit'                                              ), // 2025.03.14 [IANA: FloGraphIt]
      ( Extension: '.gpx';         MimeType: 'application/gpx+xml'                                                     ), // 2025.03.14 [GPS eXchange Format]
      ( Extension: '.gqf';         MimeType: 'application/vnd.grafeq'                                                  ), // 2025.03.14 [IANA: GrafEq]
      ( Extension: '.gram';        MimeType: 'application/srgs'                                                        ), // 2025.03.14 [W3C Speech Grammar]
      ( Extension: '.grv';         MimeType: 'application/vnd.groove-injector'                                         ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.grxml';       MimeType: 'application/srgs+xml'                                                    ), // 2025.03.14 [W3C Speech Grammar]
      ( Extension: '.gsf';         MimeType: 'application/x-font-ghostscript'                                          ), // 2025.03.14 [Wikipedia: Ghostscript]
      ( Extension: '.gsm';         MimeType: 'audio/x-gsm'                                                             ), // Indy 10.6.3.2
      ( Extension: '.gtar';        MimeType: 'application/x-gtar'                                                      ), // 2025.03.14 [GNU Tar]
      ( Extension: '.gtm';         MimeType: 'application/vnd.groove-tool-message'                                     ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.gtw';         MimeType: 'model/vnd.gtw'                                                           ), // 2025.03.14 [IANA: GTW]
      ( Extension: '.gv';          MimeType: 'text/vnd.graphviz'                                                       ), // 2025.03.14 [IANA: Graphviz]
      ( Extension: '.gxt';         MimeType: 'application/vnd.geonext'                                                 ), // 2025.03.14 [IANA: GEONExT and JSXGraph]
      ( Extension: '.gz';          MimeType: 'application/x-gzip'                                                      ), // Indy 10.6.3.2
      ( Extension: '.gz';          MimeType: 'application/gzip'                                                        ), // 2025.03.14 [Wikipedia: GZip]
      ( Extension: '.gzip';        MimeType: 'application/x-gzip'                                                      ), // Indy 10.6.3.2
      ( Extension: '.h';           MimeType: 'text/x-chdr'                                                             ), // Indy 10.6.3.2
      ( Extension: '.h++';         MimeType: 'text/x-c++hdr'                                                           ), // Indy 10.6.3.2
      ( Extension: '.h261';        MimeType: 'video/h261'                                                              ), // 2025.03.14 [Wikipedia: H.261]
      ( Extension: '.h263';        MimeType: 'video/h263'                                                              ), // 2025.03.14 [Wikipedia: H.263]
      ( Extension: '.h264';        MimeType: 'video/h264'                                                              ), // 2025.03.14 [Wikipedia: H.264]
      ( Extension: '.hal';         MimeType: 'application/vnd.hal+xml'                                                 ), // 2025.03.14 [IANA: HAL]
      ( Extension: '.hbci';        MimeType: 'application/vnd.hbci'                                                    ), // 2025.03.14 [IANA: HBCI]
      ( Extension: '.hdf';         MimeType: 'application/x-hdf'                                                       ), // 2025.03.14 [Wikipedia: Hierarchical Data Format]
      ( Extension: '.hh';          MimeType: 'text/x-c++hdr'                                                           ), // Indy 10.6.3.2
      ( Extension: '.hlp';         MimeType: 'application/winhlp'                                                      ), // 2025.03.14 [Wikipedia: WinHelp]
      ( Extension: '.hpf';         MimeType: 'application/x-icq-hpf'                                                   ), // Indy 10.6.3.2
      ( Extension: '.hpgl';        MimeType: 'application/vnd.hp-hpgl'                                                 ), // 2025.03.14 [IANA: HP-GL/2 and HP RTL]
      ( Extension: '.hpid';        MimeType: 'application/vnd.hp-hpid'                                                 ), // 2025.03.14 [IANA: Hewlett Packard Instant Delivery]
      ( Extension: '.hpp';         MimeType: 'text/x-c++hdr'                                                           ), // Indy 10.6.3.2
      ( Extension: '.hps';         MimeType: 'application/vnd.hp-hps'                                                  ), // 2025.03.14 [IANA: Hewlett-Packard's WebPrintSmart]
      ( Extension: '.hqx';         MimeType: 'application/mac-binhex40'                                                ), // 2025.03.14 [MacMIME]
      ( Extension: '.hta';         MimeType: 'application/hta'                                                         ), // Indy 10.6.3.2
      ( Extension: '.htc';         MimeType: 'text/x-component'                                                        ), // Indy 10.6.3.2
      ( Extension: '.htke';        MimeType: 'application/vnd.kenameaapp'                                              ), // 2025.03.14 [IANA: Kenamea App]
      ( Extension: '.htm';         MimeType: 'text/html'                                                               ), // Indy 10.6.3.2
      ( Extension: '.html';        MimeType: 'text/html'                                                               ), // 2025.03.14 [Wikipedia: HTML]
      ( Extension: '.htt';         MimeType: 'text/webviewhtml'                                                        ), // Indy 10.6.3.2
      ( Extension: '.hvd';         MimeType: 'application/vnd.yamaha.hv-dic'                                           ), // 2025.03.14 [IANA: HV Voice Dictionary]
      ( Extension: '.hvp';         MimeType: 'application/vnd.yamaha.hv-voice'                                         ), // 2025.03.14 [IANA: HV Voice Parameter]
      ( Extension: '.hvs';         MimeType: 'application/vnd.yamaha.hv-script'                                        ), // 2025.03.14 [IANA: HV Script]
      ( Extension: '.hxx';         MimeType: 'text/x-c++hdr'                                                           ), // Indy 10.6.3.2
      ( Extension: '.i2g';         MimeType: 'application/vnd.intergeo'                                                ), // 2025.03.14 [IANA: Interactive Geometry Software]
      ( Extension: '.icc';         MimeType: 'application/vnd.iccprofile'                                              ), // 2025.03.14 [IANA: ICC profile]
      ( Extension: '.ice';         MimeType: 'x-conference/x-cooltalk'                                                 ), // 2025.03.14 [Wikipedia: CoolTalk]
      ( Extension: '.ico';         MimeType: 'image/x-icon'                                                            ), // 2025.03.14 [Wikipedia: ICO File Format]
      ( Extension: '.ics';         MimeType: 'text/calendar'                                                           ), // 2025.03.14 [Wikipedia: iCalendar]
      ( Extension: '.ief';         MimeType: 'image/ief'                                                               ), // 2025.03.14 [RFC 1314]
      ( Extension: '.ifm';         MimeType: 'application/vnd.shana.informed.formdata'                                 ), // 2025.03.14 [IANA: Shana Informed Filler]
      ( Extension: '.igl';         MimeType: 'application/vnd.igloader'                                                ), // 2025.03.14 [IANA: igLoader]
      ( Extension: '.igm';         MimeType: 'application/vnd.insors.igm'                                              ), // 2025.03.14 [IANA: IOCOM Visimeet]
      ( Extension: '.igs';         MimeType: 'model/iges'                                                              ), // 2025.03.14 [Wikipedia: IGES]
      ( Extension: '.igx';         MimeType: 'application/vnd.micrografx.igx'                                          ), // 2025.03.14 [IANA: Micrografx]
      ( Extension: '.iif';         MimeType: 'application/vnd.shana.informed.interchange'                              ), // 2025.03.14 [IANA: Shana Informed Filler]
      ( Extension: '.iii';         MimeType: 'application/x-iphone'                                                    ), // Indy 10.6.3.2
      ( Extension: '.imp';         MimeType: 'application/vnd.accpac.simply.imp'                                       ), // 2025.03.14 [IANA: Simply Accounting]
      ( Extension: '.ims';         MimeType: 'application/vnd.ms-ims'                                                  ), // 2025.03.14 [IANA: MS Class Server]
      ( Extension: '.ins';         MimeType: 'application/x-internet-signup'                                           ), // Indy 10.6.3.2
      ( Extension: '.ipfix';       MimeType: 'application/ipfix'                                                       ), // 2025.03.14 [RFC 3917]
      ( Extension: '.ipk';         MimeType: 'application/vnd.shana.informed.package'                                  ), // 2025.03.14 [IANA: Shana Informed Filler]
      ( Extension: '.irm';         MimeType: 'application/vnd.ibm.rights-management'                                   ), // 2025.03.14 [IANA: IBM DB2 Rights Manager]
      ( Extension: '.irp';         MimeType: 'application/vnd.irepository.package+xml'                                 ), // 2025.03.14 [IANA: iRepository / Lucidoc Editor]
      ( Extension: '.iso';         MimeType: 'application/x-iso9660-image'                                             ), // Indy 10.6.3.2
      ( Extension: '.itp';         MimeType: 'application/vnd.shana.informed.formtemplate'                             ), // 2025.03.14 [IANA: Shana Informed Filler]
      ( Extension: '.ivf';         MimeType: 'video/x-ivf'                                                             ), // Indy 10.6.3.2
      ( Extension: '.ivp';         MimeType: 'application/vnd.immervision-ivp'                                         ), // 2025.03.14 [IANA: ImmerVision PURE Players]
      ( Extension: '.ivu';         MimeType: 'application/vnd.immervision-ivu'                                         ), // 2025.03.14 [IANA: ImmerVision PURE Players]
      ( Extension: '.jad';         MimeType: 'text/vnd.sun.j2me.app-descriptor'                                        ), // 2025.03.14 [IANA: J2ME App Descriptor]
      ( Extension: '.jam';         MimeType: 'application/vnd.jam'                                                     ), // 2025.03.14 [IANA: Lightspeed Audio Lab]
      ( Extension: '.jar';         MimeType: 'application/java-archive'                                                ), // 2025.03.14 [Wikipedia: JAR file format]
      ( Extension: '.java';        MimeType: 'text/x-java'                                                             ), // Indy 10.6.3.2
      ( Extension: '.java';        MimeType: 'text/x-java-source,java'                                                 ), // 2025.03.14 [Wikipedia: Java]
      ( Extension: '.jisp';        MimeType: 'application/vnd.jisp'                                                    ), // 2025.03.14 [IANA: RhymBox]
      ( Extension: '.jlt';         MimeType: 'application/vnd.hp-jlyt'                                                 ), // 2025.03.14 [IANA: HP Job Layout Language]
      ( Extension: '.jng';         MimeType: 'image/x-jng'                                                             ), // Indy 10.6.3.2
      ( Extension: '.jp2';         MimeType: 'image/jp2'                                                               ), // [RFC 3745]
      ( Extension: '.jpx';         MimeType: 'image/jpx'                                                               ), // [RFC 3745]
      ( Extension: '.jnlp';        MimeType: 'application/x-java-jnlp-file'                                            ), // 2025.03.14 [Wikipedia: Java Web Start]
      ( Extension: '.joda';        MimeType: 'application/vnd.joost.joda-archive'                                      ), // 2025.03.14 [IANA: Joda Archive]
      ( Extension: '.jpe';         MimeType: 'image/jpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.jpeg';        MimeType: 'image/jpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.jpg';         MimeType: 'image/jpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.jpgv';        MimeType: 'video/jpeg'                                                              ), // 2025.03.14 [RFC 3555]
      ( Extension: '.jpm';         MimeType: 'video/jpm'                                                               ), // 2025.03.14 [IANA: JPM]
      ( Extension: '.js';          MimeType: 'text/javascript'                                                         ), // Indy 10.6.3.2
      ( Extension: '.js';          MimeType: 'application/javascript'                                                  ), // 2025.03.14 [JavaScript]
      ( Extension: '.jsf';         MimeType: 'text/plain'                                                              ), // 2025.11.22 [Gemini AI]
      ( Extension: '.json';        MimeType: 'application/json'                                                        ), // 2025.03.14 [Wikipedia: JSON]
      ( Extension: '.jsonld';      MimeType: 'application/ld+json'                                                     ), // 2025.03.14 [Wikipedia: JSON-LD]

      ( Extension: '.kar';         MimeType: 'audio/midi'                                                              ), // Indy 10.6.3.2
      ( Extension: '.karbon';      MimeType: 'application/vnd.kde.karbon'                                              ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.kdelnk';      MimeType: 'application/x-kde-link'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.kfo';         MimeType: 'application/vnd.kde.kformula'                                            ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.kia';         MimeType: 'application/vnd.kidspiration'                                            ), // 2025.03.14 [IANA: Kidspiration]
      ( Extension: '.kml';         MimeType: 'application/vnd.google-earth.kml+xml'                                    ), // 2025.03.14 [IANA: Google Earth]
      ( Extension: '.kmz';         MimeType: 'application/vnd.google-earth.kmz'                                        ), // 2025.03.14 [IANA: Google Earth]
      ( Extension: '.kne';         MimeType: 'application/vnd.kinar'                                                   ), // 2025.03.14 [IANA: Kina Applications]
      ( Extension: '.kon';         MimeType: 'application/vnd.kde.kontour'                                             ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.kpr';         MimeType: 'application/vnd.kde.kpresenter'                                          ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.kpt';         MimeType: 'application/vnd.kde.kpresenter'                                          ), // Indy 10.6.3.2
      ( Extension: '.ksp';         MimeType: 'application/vnd.kde.kspread'                                             ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.ktx';         MimeType: 'image/ktx'                                                               ), // 2025.03.14 [KTX File Format]
      ( Extension: '.ktz';         MimeType: 'application/vnd.kahootz'                                                 ), // 2025.03.14 [IANA: Kahootz]
      ( Extension: '.kwd';         MimeType: 'application/vnd.kde.kword'                                               ), // 2025.03.14 [IANA: KDE KOffice Office Suite]
      ( Extension: '.kwt';         MimeType: 'application/vnd.kde.kword'                                               ), // Indy 10.6.3.2
      ( Extension: '.lasxml';      MimeType: 'application/vnd.las.las+xml'                                             ), // 2025.03.14 [IANA: Laser App Enterprise]
      ( Extension: '.latex';       MimeType: 'application/x-latex'                                                     ), // 2025.03.14 [Wikipedia: LaTeX]
      ( Extension: '.lbd';         MimeType: 'application/vnd.llamagraphics.life-balance.desktop'                      ), // 2025.03.14 [IANA: Life Balance]
      ( Extension: '.lbe';         MimeType: 'application/vnd.llamagraphics.life-balance.exchange+xml'                 ), // 2025.03.14 [IANA: Life Balance]
      ( Extension: '.lcc';         MimeType: 'application/fastman'                                                     ), // Indy 10.6.3.2
      ( Extension: '.les';         MimeType: 'application/vnd.hhe.lesson-player'                                       ), // 2025.03.14 [IANA: Archipelago Lesson Player]
      ( Extension: '.lha';         MimeType: 'application/x-lzh'                                                       ), // Indy 10.6.3.2
      ( Extension: '.link66';      MimeType: 'application/vnd.route66.link66+xml'                                      ), // 2025.03.14 [IANA: ROUTE 66]
      ( Extension: '.lrm';         MimeType: 'application/vnd.ms-lrm'                                                  ), // 2025.03.14 [IANA: MS Learning Resource Module]
      ( Extension: '.ls';          MimeType: 'text/javascript'                                                         ), // Indy 10.6.3.2
      ( Extension: '.lsf';         MimeType: 'video/x-la-asf'                                                          ), // Indy 10.6.3.2
      ( Extension: '.lsx';         MimeType: 'video/x-la-asf'                                                          ), // Indy 10.6.3.2
      ( Extension: '.ltf';         MimeType: 'application/vnd.frogans.ltf'                                             ), // 2025.03.14 [IANA: Frogans Player]
      ( Extension: '.lvp';         MimeType: 'audio/vnd.lucent.voice'                                                  ), // 2025.03.14 [IANA: Lucent Voice]
      ( Extension: '.lwp';         MimeType: 'application/vnd.lotus-wordpro'                                           ), // 2025.03.14 [IANA: Lotus Wordpro]
      ( Extension: '.lz';          MimeType: 'application/x-lzip'                                                      ), // Indy 10.6.3.2
      ( Extension: '.lzh';         MimeType: 'application/x-lzh'                                                       ), // Indy 10.6.3.2
      ( Extension: '.lzma';        MimeType: 'application/x-lzma'                                                      ), // Indy 10.6.3.2
      ( Extension: '.lzo';         MimeType: 'application/x-lzop'                                                      ), // Indy 10.6.3.2
      ( Extension: '.lzx';         MimeType: 'application/x-lzx'                                                       ), // Indy 10.6.3.2
      ( Extension: '.m13';         MimeType: 'application/x-msmediaview'                                               ), // Indy 10.6.3.2
      ( Extension: '.m14';         MimeType: 'application/x-msmediaview'                                               ), // Indy 10.6.3.2
      ( Extension: '.m21';         MimeType: 'application/mp21'                                                        ), // 2025.03.14 [Wikipedia: MPEG-21]
      ( Extension: '.m3u';         MimeType: 'audio/mpegurl'                                                           ), // Indy 10.6.3.2
      ( Extension: '.m3u';         MimeType: 'audio/x-mpegurl'                                                         ), // 2025.03.14 [Wikipedia: M3U]
      ( Extension: '.m3u8';        MimeType: 'application/x-mpegurl'                                                   ), // 2025.11.30 [https://help.encoding.com/knowledge-base/article/correct-mime-types-for-serving-video-files/]
      ( Extension: '.m3u8';        MimeType: 'application/vnd.apple.mpegurl'                                           ), // 2025.03.14 [Wikipedia: M3U]
      ( Extension: '.m4a';         MimeType: 'audio/x-mpg'                                                             ), // Indy 10.6.3.2
      ( Extension: '.m4v';         MimeType: 'video/x-m4v'                                                             ), // 2025.03.14 [Wikipedia: M4v]
      ( Extension: '.ma';          MimeType: 'application/mathematica'                                                 ), // 2025.03.14 [IANA - Mathematica]
      ( Extension: '.mads';        MimeType: 'application/mads+xml'                                                    ), // 2025.03.14 [RFC 6207]
      ( Extension: '.mag';         MimeType: 'application/vnd.ecowin.chart'                                            ), // 2025.03.14 [IANA: EcoWin Chart]
      ( Extension: '.man';         MimeType: 'application/x-troff-man'                                                 ), // Indy 10.6.3.2
      ( Extension: '.mathml';      MimeType: 'application/mathml+xml'                                                  ), // 2025.03.14 [W3C Math Home]
      ( Extension: '.mbk';         MimeType: 'application/vnd.mobius.mbk'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.mbox';        MimeType: 'application/mbox'                                                        ), // 2025.03.14 [RFC 4155]
      ( Extension: '.mc1';         MimeType: 'application/vnd.medcalcdata'                                             ), // 2025.03.14 [IANA: MedCalc]
      ( Extension: '.mcd';         MimeType: 'application/vnd.mcd'                                                     ), // 2025.03.14 [IANA: Micro CADAM Helix D&D]
      ( Extension: '.mcurl';       MimeType: 'text/vnd.curl.mcurl'                                                     ), // 2025.03.14 [Curl Manifest File]
      ( Extension: '.mdb';         MimeType: 'application/x-msaccess'                                                  ), // 2025.03.14 [Wikipedia: Microsoft Access]
      ( Extension: '.mdi';         MimeType: 'image/vnd.ms-modi'                                                       ), // 2025.03.14 [Wikipedia: Microsoft Document Image Format]
      ( Extension: '.me';          MimeType: 'application/x-troff-me'                                                  ), // Indy 10.6.3.2
      ( Extension: '.meta4';       MimeType: 'application/metalink4+xml'                                               ), // 2025.03.14 [Wikipedia: Metalink]
      ( Extension: '.mets';        MimeType: 'application/mets+xml'                                                    ), // 2025.03.14 [RFC 6207]
      ( Extension: '.mfm';         MimeType: 'application/vnd.mfmp'                                                    ), // 2025.03.14 [IANA: Melody Format for Mobile Platform]
      ( Extension: '.mgp';         MimeType: 'application/vnd.osgeo.mapguide.package'                                  ), // 2025.03.14 [IANA: MapGuide DBXML]
      ( Extension: '.mgz';         MimeType: 'application/vnd.proteus.magazine'                                        ), // 2025.03.14 [IANA: EFI Proteus]
      ( Extension: '.mht';         MimeType: 'message/rfc822'                                                          ), // Indy 10.6.3.2
      ( Extension: '.mid';         MimeType: 'audio/midi'                                                              ), // 2025.03.14 [Wikipedia: MIDI]
      ( Extension: '.midi';        MimeType: 'audio/midi'                                                              ), // 2025.03.14 [Wikipedia: MIDI]
      ( Extension: '.mif';         MimeType: 'application/vnd.mif'                                                     ), // 2025.03.14 [IANA: FrameMaker Interchange Format]
      ( Extension: '.mj2';         MimeType: 'video/mj2'                                                               ), // 2025.03.14 [IANA: MJ2]
      ( Extension: '.mjf';         MimeType: 'audio/x-vnd.AudioExplosion.MjuiceMediaFile'                              ), // Indy 10.6.3.2
      ( Extension: '.mjs';         MimeType: 'text/javascript'                                                         ), // 2025.03.14 [Wikipedia: Javascript]
      ( Extension: '.mjs';         MimeType: 'text/javascript'                                                         ), // 2025.03.14 [ECMAScript modules]
      ( Extension: '.ml';          MimeType: 'animation/narrative'                                                     ), // Indy 10.6.3.2
      ( Extension: '.mlp';         MimeType: 'application/vnd.dolby.mlp'                                               ), // 2025.03.14 [IANA: Dolby Meridian Lossless Packing]
      ( Extension: '.mmd';         MimeType: 'application/vnd.chipnuts.karaoke-mmd'                                    ), // 2025.03.14 [IANA: Chipnuts Karaoke]
      ( Extension: '.mmf';         MimeType: 'application/vnd.smaf'                                                    ), // 2025.03.14 [IANA: SMAF File]
      ( Extension: '.mmr';         MimeType: 'image/vnd.fujixerox.edmics-mmr'                                          ), // 2025.03.14 [IANA: EDMICS 2000]
      ( Extension: '.mng';         MimeType: 'video/x-mng'                                                             ), // Indy 10.6.3.2
      ( Extension: '.mny';         MimeType: 'application/x-msmoney'                                                   ), // 2025.03.14 [Wikipedia: Microsoft Money]
      ( Extension: '.mobi';        MimeType: 'application/x-mobipocket-ebook'                                          ), // 2025.03.18
      ( Extension: '.mocha';       MimeType: 'text/javascript'                                                         ), // Indy 10.6.3.2
      ( Extension: '.mods';        MimeType: 'application/mods+xml'                                                    ), // 2025.03.14 [RFC 6207]
      ( Extension: '.moov';        MimeType: 'video/quicktime'                                                         ), // Indy 10.6.3.2
      ( Extension: '.mov';         MimeType: 'video/quicktime'                                                         ), // Indy 10.6.3.2
      ( Extension: '.movie';       MimeType: 'video/x-sgi-movie'                                                       ), // 2025.03.14 [SGI Facts]
      ( Extension: '.mp2';         MimeType: 'audio/x-mpg'                                                             ), // Indy 10.6.3.2
      ( Extension: '.mp2';         MimeType: 'video/mpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.mp3';         MimeType: 'audio/x-mpg'                                                             ), // Indy 10.6.3.2
      ( Extension: '.mp3';         MimeType: 'video/mpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.mp4';         MimeType: 'video/mp4'                                                               ), // 2025.03.14 [MPEG-4 Video]
      ( Extension: '.mp4';         MimeType: 'video/mpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.mp4';         MimeType: 'application/mp4'                                                         ), // 2025.03.14 [RFC 4337]
      ( Extension: '.mp4a';        MimeType: 'audio/mp4'                                                               ), // 2025.03.14 [MPEG-4 Audio]
      ( Extension: '.mpa';         MimeType: 'video/mpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.mpc';         MimeType: 'application/vnd.mophun.certificate'                                      ), // 2025.03.14 [IANA: Mophun Certificate]
      ( Extension: '.mpe';         MimeType: 'video/mpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.mpeg';        MimeType: 'video/x-mpeg2a'                                                          ), // Indy 10.6.3.2
      ( Extension: '.mpeg';        MimeType: 'video/mpeg'                                                              ), // 2025.03.14 [Wikipedia: MPEG]
      ( Extension: '.mpega';       MimeType: 'audio/x-mpg'                                                             ), // Indy 10.6.3.2
      ( Extension: '.mpg';         MimeType: 'video/mpeg'                                                              ), // Indy 10.6.3.2
      ( Extension: '.mpga';        MimeType: 'audio/x-mpg'                                                             ), // Indy 10.6.3.2
      ( Extension: '.mpga';        MimeType: 'audio/mpeg'                                                              ), // 2025.03.14 [Wikipedia: MPGA]
      ( Extension: '.mpkg';        MimeType: 'vnd.apple.installer+xml'                                                 ), // Indy 10.6.3.2
      ( Extension: '.mpkg';        MimeType: 'application/vnd.apple.installer+xml'                                     ), // 2025.03.14 [IANA: Apple Installer]
      ( Extension: '.mpm';         MimeType: 'application/vnd.blueice.multipass'                                       ), // 2025.03.14 [IANA: Multipass]
      ( Extension: '.mpn';         MimeType: 'application/vnd.mophun.application'                                      ), // 2025.03.14 [IANA: Mophun VM]
      ( Extension: '.mpp';         MimeType: 'application/vnd.ms-project'                                              ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.mpy';         MimeType: 'application/vnd.ibm.minipay'                                             ), // 2025.03.14 [IANA: MiniPay]
      ( Extension: '.mqy';         MimeType: 'application/vnd.mobius.mqy'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.mrc';         MimeType: 'application/marc'                                                        ), // 2025.03.14 [RFC 2220]
      ( Extension: '.mrcx';        MimeType: 'application/marcxml+xml'                                                 ), // 2025.03.14 [RFC 6207]
      ( Extension: '.ms';          MimeType: 'application/x-troff-ms'                                                  ), // Indy 10.6.3.2
      ( Extension: '.mscml';       MimeType: 'application/mediaservercontrol+xml'                                      ), // 2025.03.14 [RFC 5022]
      ( Extension: '.mseq';        MimeType: 'application/vnd.mseq'                                                    ), // 2025.03.14 [IANA: 3GPP MSEQ File]
      ( Extension: '.msf';         MimeType: 'application/vnd.epson.msf'                                               ), // 2025.03.14 [IANA: QUASS Stream Player]
      ( Extension: '.msh';         MimeType: 'model/mesh'                                                              ), // 2025.03.14 [RFC 2077]
      ( Extension: '.msi';         MimeType: 'application/x-msi'                                                       ), // Indy 10.6.3.2
      ( Extension: '.msl';         MimeType: 'application/vnd.mobius.msl'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.msty';        MimeType: 'application/vnd.muvee.style'                                             ), // 2025.03.14 [IANA: Muvee]
      ( Extension: '.mts';         MimeType: 'model/vnd.mts'                                                           ), // 2025.03.14 [IANA: MTS]
      ( Extension: '.mus';         MimeType: 'application/vnd.musician'                                                ), // 2025.03.14 [IANA: MUSICIAN]
      ( Extension: '.musicxml';    MimeType: 'application/vnd.recordare.musicxml+xml'                                  ), // 2025.03.14 [IANA: Recordare Apps]
      ( Extension: '.mvb';         MimeType: 'application/x-msmediaview'                                               ), // 2025.03.14 [Windows Help]
      ( Extension: '.mwf';         MimeType: 'application/vnd.mfer'                                                    ), // 2025.03.14 [IANA: Medical Waveform Encoding Format]
      ( Extension: '.mxf';         MimeType: 'application/mxf'                                                         ), // 2025.03.14 [RFC 4539]
      ( Extension: '.mxl';         MimeType: 'application/vnd.recordare.musicxml'                                      ), // 2025.03.14 [IANA: Recordare Apps]
      ( Extension: '.mxml';        MimeType: 'application/xv+xml'                                                      ), // 2025.03.14 [Wikipedia: MXML]
      ( Extension: '.mxs';         MimeType: 'application/vnd.triscape.mxs'                                            ), // 2025.03.14 [IANA: Triscape Map Explorer]
      ( Extension: '.mxu';         MimeType: 'video/vnd.mpegurl'                                                       ), // 2025.03.14 [IANA: MPEG Url]
      ( Extension: '.n3';          MimeType: 'text/n3'                                                                 ), // 2025.03.14 [Wikipedia: Notation3]
      ( Extension: '.nbp';         MimeType: 'application/vnd.wolfram.player'                                          ), // 2025.03.14 [IANA: Mathematica Notebook Player]
      ( Extension: '.nc';          MimeType: 'application/x-netcdf'                                                    ), // 2025.03.14 [Wikipedia: NetCDF]
      ( Extension: '.ncx';         MimeType: 'application/x-dtbncx+xml'                                                ), // 2025.03.14 [Wikipedia: EPUB]
      ( Extension: '.n-gage';      MimeType: 'application/vnd.nokia.n-gage.symbian.install'                            ), // 2025.03.14 [IANA: N-Gage Game Installer]
      ( Extension: '.ngdat';       MimeType: 'application/vnd.nokia.n-gage.data'                                       ), // 2025.03.14 [IANA: N-Gage Game Data]
      ( Extension: '.nix';         MimeType: 'application/x-mix-transfer'                                              ), // Indy 10.6.3.2
      ( Extension: '.nlu';         MimeType: 'application/vnd.neurolanguage.nlu'                                       ), // 2025.03.14 [IANA: neuroLanguage]
      ( Extension: '.nml';         MimeType: 'application/vnd.enliven'                                                 ), // 2025.03.14 [IANA: Enliven Viewer]
      ( Extension: '.nnd';         MimeType: 'application/vnd.noblenet-directory'                                      ), // 2025.03.14 [IANA: NobleNet Directory]
      ( Extension: '.nns';         MimeType: 'application/vnd.noblenet-sealer'                                         ), // 2025.03.14 [IANA: NobleNet Sealer]
      ( Extension: '.nnw';         MimeType: 'application/vnd.noblenet-web'                                            ), // 2025.03.14 [IANA: NobleNet Web]
      ( Extension: '.npx';         MimeType: 'image/vnd.net-fpx'                                                       ), // 2025.03.14 [IANA: FPX]
      ( Extension: '.nsf';         MimeType: 'application/vnd.lotus-notes'                                             ), // 2025.03.14 [IANA: Lotus Notes]
      ( Extension: '.o';           MimeType: 'application/x-object'                                                    ), // Indy 10.6.3.2
      ( Extension: '.oa2';         MimeType: 'application/vnd.fujitsu.oasys2'                                          ), // 2025.03.14 [IANA: Fujitsu Oasys]
      ( Extension: '.oa3';         MimeType: 'application/vnd.fujitsu.oasys3'                                          ), // 2025.03.14 [IANA: Fujitsu Oasys]
      ( Extension: '.oas';         MimeType: 'application/vnd.fujitsu.oasys'                                           ), // 2025.03.14 [IANA: Fujitsu Oasys]
      ( Extension: '.obd';         MimeType: 'application/x-msbinder'                                                  ), // 2025.03.14 [Wikipedia: Microsoft Shared Tools]
      ( Extension: '.oda';         MimeType: 'application/oda'                                                         ), // 2025.03.14 [RFC 2161]
      ( Extension: '.odb';         MimeType: 'application/vnd.oasis.opendocument.database'                             ), // 2025.03.14 [IANA: OpenDocument Database]
      ( Extension: '.odc';         MimeType: 'application/vnd.oasis.opendocument.chart'                                ), // 2025.03.14 [IANA: OpenDocument Chart]
      ( Extension: '.odf';         MimeType: 'application/vnd.oasis.opendocument.formula'                              ), // 2025.03.14 [IANA: OpenDocument Formula]
      ( Extension: '.odft';        MimeType: 'application/vnd.oasis.opendocument.formula-template'                     ), // 2025.03.14 [IANA: OpenDocument Formula Template]
      ( Extension: '.odg';         MimeType: 'application/vnd.oasis.opendocument.graphics'                             ), // 2025.03.14 [IANA: OpenDocument Graphics]
      ( Extension: '.odi';         MimeType: 'application/vnd.oasis.opendocument.image'                                ), // 2025.03.14 [IANA: OpenDocument Image]
      ( Extension: '.odm';         MimeType: 'application/vnd.oasis.opendocument.text-master'                          ), // 2025.03.14 [IANA: OpenDocument Text Master]
      ( Extension: '.odp';         MimeType: 'application/vnd.oasis.opendocument.presentation'                         ), // 2025.03.14 [IANA: OpenDocument Presentation]
      ( Extension: '.ods';         MimeType: 'application/vnd.oasis.opendocument.spreadsheet'                          ), // 2025.03.14 [IANA: OpenDocument Spreadsheet]
      ( Extension: '.odt';         MimeType: 'application/vnd.oasis.opendocument.text'                                 ), // 2025.03.14 [IANA: OpenDocument Text]
      ( Extension: '.oga';         MimeType: 'audio/ogg'                                                               ), // 2025.03.14 [Wikipedia: Ogg]
      ( Extension: '.ogg';         MimeType: 'application/ogg'                                                         ), // Indy 10.6.3.2
      ( Extension: '.ogv';         MimeType: 'video/ogg'                                                               ), // 2025.03.14 [Wikipedia: Ogg]
      ( Extension: '.ogx';         MimeType: 'application/ogg'                                                         ), // 2025.03.14 [Wikipedia: Ogg]
      ( Extension: '.onetoc';      MimeType: 'application/onenote'                                                     ), // 2025.03.14 [MS OneNote 2010]
      ( Extension: '.opf';         MimeType: 'application/oebps-package+xml'                                           ), // 2025.03.14 [Wikipedia: Open eBook]
      ( Extension: '.opus';        MimeType: 'audio/opus'                                                              ), // 2025.03.14 [Wikipedia: Opus Audio]
      ( Extension: '.org';         MimeType: 'application/vnd.lotus-organizer'                                         ), // 2025.03.14 [IANA: Lotus Organizer]
      ( Extension: '.osf';         MimeType: 'application/vnd.yamaha.openscoreformat'                                  ), // 2025.03.14 [IANA: Open Score Format]
      ( Extension: '.osfpvg';      MimeType: 'application/vnd.yamaha.openscoreformat.osfpvg+xml'                       ), // 2025.03.14 [IANA: OSFPVG]
      ( Extension: '.otc';         MimeType: 'application/vnd.oasis.opendocument.chart-template'                       ), // 2025.03.14 [IANA: OpenDocument Chart Template]
      ( Extension: '.otf';         MimeType: 'application/x-font-otf'                                                  ), // 2025.03.14 [OpenType Font File]
      ( Extension: '.otg';         MimeType: 'application/vnd.oasis.opendocument.graphics-template'                    ), // 2025.03.14 [IANA: OpenDocument Graphics Template]
      ( Extension: '.oth';         MimeType: 'application/vnd.oasis.opendocument.text-web'                             ), // 2025.03.14 [IANA: OpenDocument Text Web]
      ( Extension: '.oti';         MimeType: 'application/vnd.oasis.opendocument.image-template'                       ), // 2025.03.14 [IANA: OpenDocument Image Template]
      ( Extension: '.otp';         MimeType: 'application/vnd.oasis.opendocument.presentation-template'                ), // 2025.03.14 [IANA: OpenDocument Presentation Template]
      ( Extension: '.ots';         MimeType: 'application/vnd.oasis.opendocument.spreadsheet-template'                 ), // 2025.03.14 [IANA: OpenDocument Spreadsheet Template]
      ( Extension: '.ott';         MimeType: 'application/vnd.oasis.opendocument.text-template'                        ), // 2025.03.14 [IANA: OpenDocument Text Template]
      ( Extension: '.oxt';         MimeType: 'application/vnd.openofficeorg.extension'                                 ), // 2025.03.14 [IANA: Open Office Extension]
      ( Extension: '.p';           MimeType: 'text/x-pascal'                                                           ), // 2025.03.14 [Wikipedia: Pascal]
      ( Extension: '.p10';         MimeType: 'application/pkcs10'                                                      ), // 2025.03.14 [RFC 2986]
      ( Extension: '.p12';         MimeType: 'application/x-pkcs12'                                                    ), // 2025.03.14 [RFC 2986]
      ( Extension: '.p7b';         MimeType: 'application/x-pkcs7-certificates'                                        ), // 2025.03.14 [RFC 2986]
      ( Extension: '.p7m';         MimeType: 'application/pkcs7-mime'                                                  ), // 2025.03.14 [RFC 2315]
      ( Extension: '.p7r';         MimeType: 'application/x-pkcs7-certreqresp'                                         ), // 2025.03.14 [RFC 2986]
      ( Extension: '.p7s';         MimeType: 'application/pkcs7-signature'                                             ), // 2025.03.14 [RFC 2315]
      ( Extension: '.p8';          MimeType: 'application/pkcs8'                                                       ), // 2025.03.14 [RFC 5208]
      ( Extension: '.package';     MimeType: 'application/vnd.autopackage'                                             ), // Indy 10.6.3.2
      ( Extension: '.par';         MimeType: 'text/plain-bas'                                                          ), // 2025.03.14 [Phonetik BAS]
      ( Extension: '.pas';         MimeType: 'text/x-pascal'                                                           ), // Indy 10.6.3.2
      ( Extension: '.pat';         MimeType: 'image/x-coreldrawpattern'                                                ), // Indy 10.6.3.2
      ( Extension: '.paw';         MimeType: 'application/vnd.pawaafile'                                               ), // 2025.03.14 [IANA: PawaaFILE]
      ( Extension: '.pbd';         MimeType: 'application/vnd.powerbuilder6'                                           ), // 2025.03.14 [IANA: PowerBuilder]
      ( Extension: '.pbm';         MimeType: 'image/x-portable-bitmap'                                                 ), // 2025.03.14 [Wikipedia: Netpbm Format]
      ( Extension: '.pcf';         MimeType: 'application/x-font-pcf'                                                  ), // 2025.03.14 [Wikipedia: Portable Compiled Format]
      ( Extension: '.pcl';         MimeType: 'application/vnd.hp-pcl'                                                  ), // 2025.03.14 [IANA: HP Printer Command Language]
      ( Extension: '.pclxl';       MimeType: 'application/vnd.hp-pclxl'                                                ), // 2025.03.14 [IANA: HP PCL XL]
      ( Extension: '.pcurl';       MimeType: 'application/vnd.curl.pcurl'                                              ), // 2025.03.14 [IANA: CURL Applet]
      ( Extension: '.pcx';         MimeType: 'image/pcx'                                                               ), // Indy 10.6.3.2
      ( Extension: '.pcx';         MimeType: 'image/x-pcx'                                                             ), // 2025.03.14 [Wikipedia: PCX]
      ( Extension: '.pdb';         MimeType: 'application/vnd.palm'                                                    ), // 2025.03.14 [IANA: PalmOS Data]
      ( Extension: '.pdf';         MimeType: 'application/pdf'                                                         ), // 2025.03.14 [Adobe PDF]
      ( Extension: '.pfa';         MimeType: 'application/x-font-type1'                                                ), // 2025.03.14 [Wikipedia: PostScript Fonts]
      ( Extension: '.pfr';         MimeType: 'application/font-tdpfr'                                                  ), // 2025.03.14 [RFC 3073]
      ( Extension: '.pgm';         MimeType: 'image/x-portable-graymap'                                                ), // 2025.03.14 [Wikipedia: Netpbm Format]
      ( Extension: '.pgn';         MimeType: 'application/x-chess-pgn'                                                 ), // 2025.03.14 [Wikipedia: Portable Game Notationb]
      ( Extension: '.pgp';         MimeType: 'application/pgp-encrypted'                                               ), // 2025.03.14 [RFC 2015]
      ( Extension: '.pgp';         MimeType: 'application/pgp-signature'                                               ), // 2025.03.14 [RFC 2015]
      ( Extension: '.pic';         MimeType: 'image/x-pict'                                                            ), // 2025.03.14 [Wikipedia: PICT]
      ( Extension: '.pict';        MimeType: 'image/x-pict'                                                            ), // Indy 10.6.3.2
      ( Extension: '.pjpeg';       MimeType: 'image/pjpeg'                                                             ), // 2025.03.14 [JPEG image compression FAQ]
      ( Extension: '.pkg';         MimeType: 'vnd.apple.installer+xml'                                                 ), // Indy 10.6.3.2
      ( Extension: '.pki';         MimeType: 'application/pkixcmp'                                                     ), // 2025.03.14 [RFC 2585]
      ( Extension: '.pkipath';     MimeType: 'application/pkix-pkipath'                                                ), // 2025.03.14 [RFC 2585]
      ( Extension: '.pko';         MimeType: 'application/vnd.ms-pki.pko'                                              ), // Indy 10.6.3.2
      ( Extension: '.pl';          MimeType: 'application/x-perl'                                                      ), // Indy 10.6.3.2
      ( Extension: '.plb';         MimeType: 'application/vnd.3gpp.pic-bw-large'                                       ), // 2025.03.14 [3GPP]
      ( Extension: '.plc';         MimeType: 'application/vnd.mobius.plc'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.plf';         MimeType: 'application/vnd.pocketlearn'                                             ), // 2025.03.14 [IANA: PocketLearn Viewers]
      ( Extension: '.pls';         MimeType: 'audio/x-scpls'                                                           ), // Indy 10.6.3.2
      ( Extension: '.pls';         MimeType: 'application/pls+xml'                                                     ), // 2025.03.14 [RFC 4267]
      ( Extension: '.pml';         MimeType: 'application/vnd.ctc-posml'                                               ), // 2025.03.14 [IANA: PosML]
      ( Extension: '.png';         MimeType: 'image/x-png'                                                             ), // Indy 10.6.3.2
      ( Extension: '.png';         MimeType: 'image/png'                                                               ), // 2025.03.14 [RFC 2083]
      ( Extension: '.png';         MimeType: 'image/x-citrix-png'                                                      ), // 2025.03.14 [RFC 2083]
      ( Extension: '.png';         MimeType: 'image/x-png'                                                             ), // 2025.03.14 [RFC 2083]
      ( Extension: '.pnm';         MimeType: 'image/x-portable-anymap'                                                 ), // 2025.03.14 [Wikipedia: Netpbm Format]
      ( Extension: '.pnq';         MimeType: 'application/x-icq-pnq'                                                   ), // Indy 10.6.3.2
      ( Extension: '.pntg';        MimeType: 'image/x-macpaint'                                                        ), // Indy 10.6.3.2
      ( Extension: '.portpkg';     MimeType: 'application/vnd.macports.portpkg'                                        ), // 2025.03.14 [IANA: MacPorts Port System]
      ( Extension: '.pot';         MimeType: 'application/mspowerpoint'                                                ), // Indy 10.6.3.2
      ( Extension: '.potm';        MimeType: 'application/vnd.ms-powerpoint.template.macroenabled.12'                  ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.potx';        MimeType: 'application/vnd.openxmlformats-officedocument.presentationml.template'   ), // 2025.03.14 [IANA: OOXML - Presentation Template]
      ( Extension: '.ppam';        MimeType: 'application/vnd.ms-powerpoint.addin.macroenabled.12'                     ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.ppd';         MimeType: 'application/vnd.cups-ppd'                                                ), // 2025.03.14 [IANA: Cups]
      ( Extension: '.ppm';         MimeType: 'image/x-portable-pixmap'                                                 ), // 2025.03.14 [Wikipedia: Netpbm Format]
      ( Extension: '.pps';         MimeType: 'application/mspowerpoint'                                                ), // Indy 10.6.3.2
      ( Extension: '.ppsm';        MimeType: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12'                 ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.ppsx';        MimeType: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'  ), // 2025.03.14 [IANA: OOXML - Presentation]
      ( Extension: '.ppt';         MimeType: 'application/mspowerpoint'                                                ), // Indy 10.6.3.2
      ( Extension: '.ppt';         MimeType: 'application/vnd.ms-powerpoint'                                           ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.pptm';        MimeType: 'application/vnd.ms-powerpoint.presentation.macroenabled.12'              ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.pptx';        MimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' ), // 2025.03.14 [IANA: OOXML - Presentation]
      ( Extension: '.ppz';         MimeType: 'application/mspowerpoint'                                                ), // Indy 10.6.3.2
      ( Extension: '.prc';         MimeType: 'application/x-mobipocket-ebook'                                          ), // 2025.03.14 [Wikipedia: Mobipocket]
      ( Extension: '.pre';         MimeType: 'application/vnd.lotus-freelance'                                         ), // 2025.03.14 [IANA: Lotus Freelance]
      ( Extension: '.prf';         MimeType: 'application/pics-rules'                                                  ), // 2025.03.14 [W3C PICSRules]
      ( Extension: '.ps';          MimeType: 'application/postscript'                                                  ), // Indy 10.6.3.2
      ( Extension: '.psb';         MimeType: 'application/vnd.3gpp.pic-bw-small'                                       ), // 2025.03.14 [3GPP]
      ( Extension: '.psd';         MimeType: 'image/x-psd'                                                             ), // Indy 10.6.3.2
      ( Extension: '.psd';         MimeType: 'image/vnd.adobe.photoshop'                                               ), // 2025.03.14 [Wikipedia: Photoshop Document]
      ( Extension: '.psf';         MimeType: 'application/x-font-linux-psf'                                            ), // 2025.03.14 [PSF Fonts]
      ( Extension: '.pskcxml';     MimeType: 'application/pskc+xml'                                                    ), // 2025.03.14 [RFC 6030]
      ( Extension: '.ptid';        MimeType: 'application/vnd.pvi.ptid1'                                               ), // 2025.03.14 [IANA: Princeton Video Image]
      ( Extension: '.pub';         MimeType: 'application/x-mspublisher'                                               ), // 2025.03.14 [Wikipedia: Microsoft Publisher]
      ( Extension: '.pvb';         MimeType: 'application/vnd.3gpp.pic-bw-var'                                         ), // 2025.03.14 [3GPP]
      ( Extension: '.pwn';         MimeType: 'application/vnd.3m.post-it-notes'                                        ), // 2025.03.14 [IANA: 3M Post It Notes]
      ( Extension: '.pya';         MimeType: 'audio/vnd.ms-playready.media.pya'                                        ), // 2025.03.14 [IANA: Microsoft PlayReady Ecosystem]
      ( Extension: '.pyv';         MimeType: 'video/vnd.ms-playready.media.pyv'                                        ), // 2025.03.14 [IANA: Microsoft PlayReady Ecosystem]
      ( Extension: '.qam';         MimeType: 'application/vnd.epson.quickanime'                                        ), // 2025.03.14 [IANA: QuickAnime Player]
      ( Extension: '.qbo';         MimeType: 'application/vnd.intu.qbo'                                                ), // 2025.03.14 [IANA: Open Financial Exchange]
      ( Extension: '.qcp';         MimeType: 'audio/vnd.qcelp'                                                         ), // Indy 10.6.3.2
      ( Extension: '.qfx';         MimeType: 'application/vnd.intu.qfx'                                                ), // 2025.03.14 [IANA: Quicken]
      ( Extension: '.qps';         MimeType: 'application/vnd.publishare-delta-tree'                                   ), // 2025.03.14 [IANA: PubliShare Objects]
      ( Extension: '.qpw';         MimeType: 'application/x-quattropro'                                                ), // Indy 10.6.3.2
      ( Extension: '.qt';          MimeType: 'video/quicktime'                                                         ), // 2025.03.14 [Wikipedia: Quicktime]
      ( Extension: '.qtc';         MimeType: 'video/x-qtc'                                                             ), // Indy 10.6.3.2
      ( Extension: '.qtif';        MimeType: 'image/x-quicktime'                                                       ), // Indy 10.6.3.2
      ( Extension: '.qtl';         MimeType: 'application/x-quicktimeplayer'                                           ), // Indy 10.6.3.2
      ( Extension: '.qxd';         MimeType: 'application/vnd.quark.quarkxpress'                                       ), // 2025.03.14 [IANA: QuarkXPress]
      ( Extension: '.ra';          MimeType: 'audio/x-realaudio'                                                       ), // Indy 10.6.3.2
      ( Extension: '.ram';         MimeType: 'audio/x-pn-realaudio'                                                    ), // 2025.03.14 [Wikipedia: RealPlayer]
      ( Extension: '.rar';         MimeType: 'application/rar'                                                         ), // Indy 10.6.3.2
      ( Extension: '.rar';         MimeType: 'application/x-rar-compressed'                                            ), // 2025.03.14 [Wikipedia: RAR]
      ( Extension: '.ras';         MimeType: 'image/x-cmu-raster'                                                      ), // 2025.03.14
      ( Extension: '.rcprofile';   MimeType: 'application/vnd.ipunplugged.rcprofile'                                   ), // 2025.03.14 [IANA: IP Unplugged Roaming Client]
      ( Extension: '.rdf';         MimeType: 'application/rdf+xml'                                                     ), // 2025.03.14 [RFC 3870]
      ( Extension: '.rdz';         MimeType: 'application/vnd.data-vision.rdz'                                         ), // 2025.03.14 [IANA: Data-Vision]
      ( Extension: '.rep';         MimeType: 'application/vnd.businessobjects'                                         ), // 2025.03.14 [IANA: BusinessObjects]
      ( Extension: '.res';         MimeType: 'application/x-dtbresource+xml'                                           ), // 2025.03.14 [Digital Talking Book]
      ( Extension: '.rf';          MimeType: 'image/vnd.rn-realflash'                                                  ), // Indy 10.6.3.2
      ( Extension: '.rgb';         MimeType: 'image/x-rgb'                                                             ), // 2025.03.14 [RGB Image Format]
      ( Extension: '.rif';         MimeType: 'application/reginfo+xml'                                                 ), // 2025.03.14
      ( Extension: '.rip';         MimeType: 'audio/vnd.rip'                                                           ), // 2025.03.14 [IANA: Hit'n'Mix]
      ( Extension: '.rjs';         MimeType: 'application/vnd.rn-realsystem-rjs'                                       ), // Indy 10.6.3.2
      ( Extension: '.rl';          MimeType: 'application/resource-lists+xml'                                          ), // 2025.03.14 [RFC 4826]
      ( Extension: '.rlc';         MimeType: 'image/vnd.fujixerox.edmics-rlc'                                          ), // 2025.03.14 [IANA: EDMICS 2000]
      ( Extension: '.rld';         MimeType: 'application/resource-lists-diff+xml'                                     ), // 2025.03.14 [RFC 4826]
      ( Extension: '.rm';          MimeType: 'audio/x-pn-realaudio'                                                    ), // Indy 10.6.3.2
      ( Extension: '.rm';          MimeType: 'application/vnd.rn-realmedia'                                            ), // 2025.03.14
      ( Extension: '.rmf';         MimeType: 'application/vnd.rmf'                                                     ), // Indy 10.6.3.2
      ( Extension: '.rmp';         MimeType: 'application/vnd.rn-rn_music_package'                                     ), // Indy 10.6.3.2
      ( Extension: '.rmp';         MimeType: 'audio/x-pn-realaudio-plugin'                                             ), // 2025.03.14 [Wikipedia: RealPlayer]
      ( Extension: '.rms';         MimeType: 'video/vnd.rn-realvideo-secure'                                           ), // Indy 10.6.3.2
      ( Extension: '.rms';         MimeType: 'application/vnd.jcp.javame.midlet-rms'                                   ), // 2025.03.14 [IANA: Mobile Information Device Profile]
      ( Extension: '.rmx';         MimeType: 'application/vnd.rn-realsystem-rmx'                                       ), // Indy 10.6.3.2
      ( Extension: '.rnc';         MimeType: 'application/relax-ng-compact-syntax'                                     ), // 2025.03.14 [Relax NG]
      ( Extension: '.rnx';         MimeType: 'application/vnd.rn-realplayer'                                           ), // Indy 10.6.3.2
      ( Extension: '.rp';          MimeType: 'image/vnd.rn-realpix'                                                    ), // Indy 10.6.3.2
      ( Extension: '.rp9';         MimeType: 'application/vnd.cloanto.rp9'                                             ), // 2025.03.14 [IANA: RetroPlatform Player]
      ( Extension: '.rpm';         MimeType: 'application/x-redhat-package-manager'                                    ), // Indy 10.6.3.2
      ( Extension: '.rpss';        MimeType: 'application/vnd.nokia.radio-presets'                                     ), // 2025.03.14 [IANA: Nokia Radio Application]
      ( Extension: '.rpst';        MimeType: 'application/vnd.nokia.radio-preset'                                      ), // 2025.03.14 [IANA: Nokia Radio Application]
      ( Extension: '.rq';          MimeType: 'application/sparql-query'                                                ), // 2025.03.14 [W3C SPARQL]
      ( Extension: '.rs';          MimeType: 'application/rls-services+xml'                                            ), // 2025.03.14 [RFC 4826]
      ( Extension: '.rsd';         MimeType: 'application/rsd+xml'                                                     ), // 2025.03.14 [Wikipedia: Really Simple Discovery]
      ( Extension: '.rsml';        MimeType: 'application/vnd.rn-rsml'                                                 ), // Indy 10.6.3.2
      ( Extension: '.rss';         MimeType: 'application/rss+xml'                                                     ), // Indy 10.6.3.2
      ( Extension: '.rss, .xml';   MimeType: 'application/rss+xml'                                                     ), // 2025.03.14 [Wikipedia: RSS]
      ( Extension: '.rt';          MimeType: 'text/vnd.rn-realtext'                                                    ), // Indy 10.6.3.2
      ( Extension: '.rtf';         MimeType: 'application/rtf'                                                         ), // 2025.03.14 [Wikipedia: Rich Text Format]
      ( Extension: '.rtsp';        MimeType: 'application/x-rtsp'                                                      ), // Indy 10.6.3.2
      ( Extension: '.rtx';         MimeType: 'text/richtext'                                                           ), // 2025.03.14 [Wikipedia: Rich Text Format]
      ( Extension: '.rv';          MimeType: 'video/vnd.rn-realvideo'                                                  ), // Indy 10.6.3.2
      ( Extension: '.s';           MimeType: 'text/x-asm'                                                              ), // 2025.03.14 [Wikipedia: Assembly]
      ( Extension: '.saf';         MimeType: 'application/vnd.yamaha.smaf-audio'                                       ), // 2025.03.14 [IANA: SMAF Audio]
      ( Extension: '.sbml';        MimeType: 'application/sbml+xml'                                                    ), // 2025.03.14 [RFC 3823]
      ( Extension: '.sc';          MimeType: 'application/vnd.ibm.secure-container'                                    ), // 2025.03.14 [IANA: EMMS]
      ( Extension: '.scd';         MimeType: 'application/x-msschedule'                                                ), // 2025.03.14 [Wikipedia: Microsoft Schedule Plus]
      ( Extension: '.scm';         MimeType: 'application/x-icq-scm'                                                   ), // Indy 10.6.3.2
      ( Extension: '.scm';         MimeType: 'application/vnd.lotus-screencam'                                         ), // 2025.03.14 [IANA: Lotus Screencam]
      ( Extension: '.scq';         MimeType: 'application/scvp-cv-request'                                             ), // 2025.03.14 [RFC 5055]
      ( Extension: '.scs';         MimeType: 'application/scvp-cv-response'                                            ), // 2025.03.14 [RFC 5055]
      ( Extension: '.scurl';       MimeType: 'text/vnd.curl.scurl'                                                     ), // 2025.03.14 [Curl Source Code]
      ( Extension: '.sd2';         MimeType: 'audio/x-sd2'                                                             ), // Indy 10.6.3.2
      ( Extension: '.sda';         MimeType: 'application/vnd.stardivision.draw'                                       ), // 2025.03.14
      ( Extension: '.sdc';         MimeType: 'application/vnd.stardivision.calc'                                       ), // 2025.03.14
      ( Extension: '.sdd';         MimeType: 'application/vnd.stardivision.impress'                                    ), // 2025.03.14
      ( Extension: '.sdkm';        MimeType: 'application/vnd.solent.sdkm+xml'                                         ), // 2025.03.14 [IANA: SudokuMagic]
      ( Extension: '.sdp';         MimeType: 'application/x-sdp'                                                       ), // Indy 10.6.3.2
      ( Extension: '.sdp';         MimeType: 'application/sdp'                                                         ), // 2025.03.14 [RFC 2327]
      ( Extension: '.sdw';         MimeType: 'application/vnd.stardivision.writer'                                     ), // 2025.03.14
      ( Extension: '.see';         MimeType: 'application/vnd.seemail'                                                 ), // 2025.03.14 [IANA: SeeMail]
      ( Extension: '.seed';        MimeType: 'application/vnd.fdsn.seed'                                               ), // 2025.03.14 [IANA: SEED]
      ( Extension: '.sema';        MimeType: 'application/vnd.sema'                                                    ), // 2025.03.14 [IANA: Secured eMail]
      ( Extension: '.semd';        MimeType: 'application/vnd.semd'                                                    ), // 2025.03.14 [IANA: Secured eMail]
      ( Extension: '.semf';        MimeType: 'application/vnd.semf'                                                    ), // 2025.03.14 [IANA: Secured eMail]
      ( Extension: '.ser';         MimeType: 'application/java-serialized-object'                                      ), // 2025.03.14 [Java Serialization API]
      ( Extension: '.setpay';      MimeType: 'application/set-payment-initiation'                                      ), // 2025.03.14 [IANA: SET Payment]
      ( Extension: '.setreg';      MimeType: 'application/set-registration-initiation'                                 ), // 2025.03.14 [IANA: SET Registration]
      ( Extension: '.sfd-hdstx';   MimeType: 'application/vnd.hydrostatix.sof-data'                                    ), // 2025.03.14 [IANA: Hydrostatix Master Suite]
      ( Extension: '.sfs';         MimeType: 'application/vnd.spotfire.sfs'                                            ), // 2025.03.14 [IANA: TIBCO Spotfire]
      ( Extension: '.sgi';         MimeType: 'image/x-sgi'                                                             ), // Indy 10.6.3.2
      ( Extension: '.sgl';         MimeType: 'application/vnd.stardivision.writer-global'                              ), // 2025.03.14
      ( Extension: '.sgm';         MimeType: 'text/sgml'                                                               ), // Indy 10.6.3.2
      ( Extension: '.sgml';        MimeType: 'text/sgml'                                                               ), // 2025.03.14 [Wikipedia: SGML]
      ( Extension: '.sh';          MimeType: 'application/x-sh'                                                        ), // 2025.03.14 [Wikipedia: Bourne Shell]
      ( Extension: '.shar';        MimeType: 'application/x-shar'                                                      ), // 2025.03.14 [Wikipedia: Shell Archie]
      ( Extension: '.shf';         MimeType: 'application/shf+xml'                                                     ), // 2025.03.14 [RFC 4194]
      ( Extension: '.shtml';       MimeType: 'server-parsed-html'                                                      ), // Indy 10.6.3.2
      ( Extension: '.shw';         MimeType: 'application/presentations'                                               ), // Indy 10.6.3.2
      ( Extension: '.sid';         MimeType: 'audio/prs.sid'                                                           ), // Indy 10.6.3.2
      ( Extension: '.sis';         MimeType: 'application/vnd.symbian.install'                                         ), // 2025.03.14 [IANA: Symbian Install]
      ( Extension: '.sit';         MimeType: 'application/x-stuffit'                                                   ), // 2025.03.14 [Wikipedia: Stuffit]
      ( Extension: '.sitx';        MimeType: 'application/x-stuffitx'                                                  ), // 2025.03.14 [Wikipedia: Stuffit]
      ( Extension: '.skd';         MimeType: 'application/x-koan'                                                      ), // Indy 10.6.3.2
      ( Extension: '.skm';         MimeType: 'application/x-koan'                                                      ), // Indy 10.6.3.2
      ( Extension: '.skp';         MimeType: 'application/x-koan'                                                      ), // Indy 10.6.3.2
      ( Extension: '.skp';         MimeType: 'application/vnd.koan'                                                    ), // 2025.03.14 [IANA: SSEYO Koan Play File]
      ( Extension: '.skt';         MimeType: 'application/x-koan'                                                      ), // Indy 10.6.3.2
      ( Extension: '.sldm';        MimeType: 'application/vnd.ms-powerpoint.slide.macroenabled.12'                     ), // 2025.03.14 [IANA: MS PowerPoint]
      ( Extension: '.sldx';        MimeType: 'application/vnd.openxmlformats-officedocument.presentationml.slide'      ), // 2025.03.14 [IANA: OOXML - Presentation]
      ( Extension: '.slt';         MimeType: 'application/vnd.epson.salt'                                              ), // 2025.03.14 [IANA: SimpleAnimeLite Player]
      ( Extension: '.sm';          MimeType: 'application/vnd.stepmania.stepchart'                                     ), // 2025.03.14 [IANA: StepMania]
      ( Extension: '.smf';         MimeType: 'application/vnd.stardivision.math'                                       ), // 2025.03.14
      ( Extension: '.smi';         MimeType: 'application/smil'                                                        ), // Indy 10.6.3.2
      ( Extension: '.smi';         MimeType: 'application/smil+xml'                                                    ), // 2025.03.14 [RFC 4536]
      ( Extension: '.smil';        MimeType: 'application/smil'                                                        ), // Indy 10.6.3.2
      ( Extension: '.snd';         MimeType: 'audio/basic'                                                             ), // Indy 10.6.3.2
      ( Extension: '.snf';         MimeType: 'application/x-font-snf'                                                  ), // 2025.03.14 [Wikipedia: Server Normal Format]
      ( Extension: '.spf';         MimeType: 'application/vnd.yamaha.smaf-phrase'                                      ), // 2025.03.14 [IANA: SMAF Phrase]
      ( Extension: '.spl';         MimeType: 'application/futuresplash'                                                ), // Indy 10.6.3.2
      ( Extension: '.spl';         MimeType: 'application/x-futuresplash'                                              ), // 2025.03.14 [Wikipedia: FutureSplash Animator]
      ( Extension: '.spot';        MimeType: 'text/vnd.in3d.spot'                                                      ), // 2025.03.14 [IANA: In3D]
      ( Extension: '.spp';         MimeType: 'application/scvp-vp-response'                                            ), // 2025.03.14 [RFC 5055]
      ( Extension: '.spq';         MimeType: 'application/scvp-vp-request'                                             ), // 2025.03.14 [RFC 5055]
      ( Extension: '.src';         MimeType: 'application/x-wais-source'                                               ), // 2025.03.14 [YoLinux]
      ( Extension: '.sru';         MimeType: 'application/sru+xml'                                                     ), // 2025.03.14 [RFC 6207]
      ( Extension: '.srx';         MimeType: 'application/sparql-results+xml'                                          ), // 2025.03.14 [W3C SPARQL]
      ( Extension: '.sse';         MimeType: 'application/vnd.kodak-descriptor'                                        ), // 2025.03.14 [IANA: Kodak Storyshare]
      ( Extension: '.ssf';         MimeType: 'application/vnd.epson.ssf'                                               ), // 2025.03.14 [IANA: QUASS Stream Player]
      ( Extension: '.ssm';         MimeType: 'application/streamingmedia'                                              ), // Indy 10.6.3.2
      ( Extension: '.ssml';        MimeType: 'application/ssml+xml'                                                    ), // 2025.03.14 [W3C Speech Synthesis]
      ( Extension: '.sst';         MimeType: 'application/vnd.ms-pki.certstore'                                        ), // Indy 10.6.3.2
      ( Extension: '.st';          MimeType: 'application/vnd.sailingtracker.track'                                    ), // 2025.03.14 [IANA: SailingTracker]
      ( Extension: '.stc';         MimeType: 'application/vnd.sun.xml.calc.template'                                   ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.std';         MimeType: 'application/vnd.sun.xml.draw.template'                                   ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.stf';         MimeType: 'application/vnd.wt.stf'                                                  ), // 2025.03.14 [IANA: Worldtalk]
      ( Extension: '.sti';         MimeType: 'application/vnd.sun.xml.impress.template'                                ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.stk';         MimeType: 'application/hyperstudio'                                                 ), // 2025.03.14 [IANA - Hyperstudio]
      ( Extension: '.stl';         MimeType: 'application/vnd.ms-pki.stl'                                              ), // 2025.03.14 [IANA: MS Trust UI Provider]
      ( Extension: '.str';         MimeType: 'application/vnd.pg.format'                                               ), // 2025.03.14 [IANA: Proprietary P&G Standard Reporting System]
      ( Extension: '.stw';         MimeType: 'application/vnd.sun.xml.writer.template'                                 ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.sub';         MimeType: 'image/vnd.dvb.subtitle'                                                  ), // 2025.03.14 [Wikipedia: Closed Captioning]
      ( Extension: '.sus';         MimeType: 'application/vnd.sus-calendar'                                            ), // 2025.03.14 [IANA: ScheduleUs]
      ( Extension: '.sv4cpio';     MimeType: 'application/x-sv4cpio'                                                   ), // 2025.03.14 [Wikipedia: pax]
      ( Extension: '.sv4crc';      MimeType: 'application/x-sv4crc'                                                    ), // 2025.03.14 [Wikipedia: pax]
      ( Extension: '.svc';         MimeType: 'application/vnd.dvb.service'                                             ), // 2025.03.14 [IANA: Digital Video Broadcasting]
      ( Extension: '.svd';         MimeType: 'application/vnd.svd'                                                     ), // 2025.03.14 [IANA: SourceView Document]
      ( Extension: '.svg';         MimeType: 'image/svg+xml'                                                           ), // 2025.03.14 [Wikipedia: SVG]
      ( Extension: '.svgz';        MimeType: 'image/svg+xml'                                                           ), // Indy 10.6.3.2
      ( Extension: '.svi';         MimeType: 'application/softvision'                                                  ), // Indy 10.6.3.2
      ( Extension: '.swf';         MimeType: 'application/x-shockwave-flash'                                           ), // 2025.03.14 [Wikipedia: Adobe Flash]
      ( Extension: '.swf1';        MimeType: 'application/x-shockwave-flash'                                           ), // Indy 10.6.3.2
      ( Extension: '.swi';         MimeType: 'application/vnd.aristanetworks.swi'                                      ), // 2025.03.14 [IANA: Arista Networks Software Image]
      ( Extension: '.sxc';         MimeType: 'application/vnd.sun.xml.calc'                                            ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.sxd';         MimeType: 'application/vnd.sun.xml.draw'                                            ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.sxg';         MimeType: 'application/vnd.sun.xml.writer.global'                                   ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.sxi';         MimeType: 'application/vnd.sun.xml.impress'                                         ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.sxm';         MimeType: 'application/vnd.sun.xml.math'                                            ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.sxw';         MimeType: 'application/vnd.sun.xml.writer'                                          ), // 2025.03.14 [Wikipedia: OpenOffice]
      ( Extension: '.t';           MimeType: 'application/x-troff'                                                     ), // Indy 10.6.3.2
      ( Extension: '.t';           MimeType: 'text/troff'                                                              ), // 2025.03.14 [Wikipedia: troff]
      ( Extension: '.tao';         MimeType: 'application/vnd.tao.intent-module-archive'                               ), // 2025.03.14 [IANA: Tao Intent]
      ( Extension: '.tar';         MimeType: 'application/x-tar'                                                       ), // 2025.03.14 [Wikipedia: Tar]
      ( Extension: '.targa';       MimeType: 'image/x-targa'                                                           ), // Indy 10.6.3.2
      ( Extension: '.tbz';         MimeType: 'application/x-bzip-compressed-tar'                                       ), // Indy 10.6.3.2
      ( Extension: '.tbz2';        MimeType: 'application/x-bzip-compressed-tar'                                       ), // Indy 10.6.3.2
      ( Extension: '.tcap';        MimeType: 'application/vnd.3gpp2.tcap'                                              ), // 2025.03.14 [3GPP]
      ( Extension: '.tcl';         MimeType: 'application/x-tcl'                                                       ), // 2025.03.14 [Wikipedia: Tcl]
      ( Extension: '.teacher';     MimeType: 'application/vnd.smart.teacher'                                           ), // 2025.03.14 [IANA: SMART Technologies Apps]
      ( Extension: '.tei';         MimeType: 'application/tei+xml'                                                     ), // 2025.03.14 [RFC 6129]
      ( Extension: '.tex';         MimeType: 'application/x-tex'                                                       ), // 2025.03.14 [Wikipedia: TeX]
      ( Extension: '.texi';        MimeType: 'application/x-texinfo'                                                   ), // Indy 10.6.3.2
      ( Extension: '.texinfo';     MimeType: 'application/x-texinfo'                                                   ), // 2025.03.14 [Wikipedia: Texinfo]
      ( Extension: '.tfi';         MimeType: 'application/thraud+xml'                                                  ), // 2025.03.14 [RFC 5941]
      ( Extension: '.tfm';         MimeType: 'application/x-tex-tfm'                                                   ), // 2025.03.14 [Wikipedia: TeX Font Metric]
      ( Extension: '.tgz';         MimeType: 'application/x-compressed-tar'                                            ), // Indy 10.6.3.2
      ( Extension: '.thmx';        MimeType: 'application/vnd.ms-officetheme'                                          ), // 2025.03.14 [IANA: MS Office System Release Theme]
      ( Extension: '.tiff';        MimeType: 'image/tiff'                                                              ), // 2025.03.14 [Wikipedia: TIFF]
      ( Extension: '.tif';         MimeType: 'image/x-tiff'                                                            ), // Indy 10.6.3.2
      ( Extension: '.tlz';         MimeType: 'application/x-lzma-compressed-tar'                                       ), // Indy 10.6.3.2
      ( Extension: '.tmo';         MimeType: 'application/vnd.tmobile-livetv'                                          ), // 2025.03.14 [IANA: MobileTV]
      ( Extension: '.torrent';     MimeType: 'application/x-bittorrent'                                                ), // 2025.03.14 [Wikipedia: BitTorrent]
      ( Extension: '.tpl';         MimeType: 'application/vnd.groove-tool-template'                                    ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.tpt';         MimeType: 'application/vnd.trid.tpt'                                                ), // 2025.03.14 [IANA: TRI Systems]
      ( Extension: '.tr';          MimeType: 'application/x-troff'                                                     ), // Indy 10.6.3.2
      ( Extension: '.tra';         MimeType: 'application/vnd.trueapp'                                                 ), // 2025.03.14 [IANA: True BASIC]
      ( Extension: '.trm';         MimeType: 'application/x-msterminal'                                                ), // 2025.03.14 [Wikipedia: Terminal Server]
      ( Extension: '.troff';       MimeType: 'application/x-troff'                                                     ), // Indy 10.6.3.2
      ( Extension: '.ts';          MimeType: 'video/mp2t'                                                              ), // 2025.03.14 [Wikipedia: MPEG Transport Stream]
      ( Extension: '.ts';          MimeType: 'application/x-typescript'                                                ), // 2025.11.22 from AI Gemini 3
      ( Extension: '.tsd';         MimeType: 'application/timestamped-data'                                            ), // 2025.03.14 [RFC 5955]
      ( Extension: '.tsp';         MimeType: 'application/dsptype'                                                     ), // Indy 10.6.3.2
      ( Extension: '.tsv';         MimeType: 'text/tab-separated-values'                                               ), // 2025.03.14 [Wikipedia: TSV]
      ( Extension: '.ttf';         MimeType: 'application/x-font-ttf'                                                  ), // 2025.03.14 [Wikipedia: TrueType]
      ( Extension: '.ttl';         MimeType: 'text/turtle'                                                             ), // 2025.03.14 [Wikipedia: Turtle]
      ( Extension: '.ttz';         MimeType: 'application/t-time'                                                      ), // Indy 10.6.3.2
      ( Extension: '.twd';         MimeType: 'application/vnd.simtech-mindmapper'                                      ), // 2025.03.14 [IANA: SimTech MindMapper]
      ( Extension: '.txd';         MimeType: 'application/vnd.genomatix.tuxedo'                                        ), // 2025.03.14 [IANA: Genomatix Tuxedo Framework]
      ( Extension: '.txf';         MimeType: 'application/vnd.mobius.txf'                                              ), // 2025.03.14 [IANA: Mobius Management Systems]
      ( Extension: '.txt';         MimeType: 'text/plain'                                                              ), // 2025.03.14 [Wikipedia: Text File]
      ( Extension: '.txz';         MimeType: 'application/x-xz-compressed-tar'                                         ), // Indy 10.6.3.2
      ( Extension: '.udeb';        MimeType: 'application/x-debian-package'                                            ), // Indy 10.6.3.2
      ( Extension: '.ufd';         MimeType: 'application/vnd.ufdl'                                                    ), // 2025.03.14 [IANA: Universal Forms Description Language]
      ( Extension: '.uin';         MimeType: 'application/x-icq'                                                       ), // Indy 10.6.3.2
      ( Extension: '.uls';         MimeType: 'text/iuls'                                                               ), // Indy 10.6.3.2
      ( Extension: '.umj';         MimeType: 'application/vnd.umajin'                                                  ), // 2025.03.14 [IANA: UMAJIN]
      ( Extension: '.unityweb';    MimeType: 'application/vnd.unity'                                                   ), // 2025.03.14 [IANA: Unity 3d]
      ( Extension: '.uoml';        MimeType: 'application/vnd.uoml+xml'                                                ), // 2025.03.14 [IANA: UOML]
      ( Extension: '.uri';         MimeType: 'text/uri-list'                                                           ), // 2025.03.14 [RFC 2483]
      ( Extension: '.urls';        MimeType: 'application/x-url-list'                                                  ), // Indy 10.6.3.2
      ( Extension: '.ustar';       MimeType: 'application/x-ustar'                                                     ), // 2025.03.14 [Wikipedia: Ustar]
      ( Extension: '.utz';         MimeType: 'application/vnd.uiq.theme'                                               ), // 2025.03.14 [IANA: User Interface Quartz]
      ( Extension: '.uu';          MimeType: 'text/x-uuencode'                                                         ), // 2025.03.14 [Wikipedia: UUEncode]
      ( Extension: '.uva';         MimeType: 'audio/vnd.dece.audio'                                                    ), // 2025.03.14 [IANA: Dece Audio]
      ( Extension: '.uvh';         MimeType: 'video/vnd.dece.hd'                                                       ), // 2025.03.14 [IANA: DECE HD Video]
      ( Extension: '.uvi';         MimeType: 'image/vnd.dece.graphic'                                                  ), // 2025.03.14 [IANA: DECE Graphic]
      ( Extension: '.uvm';         MimeType: 'video/vnd.dece.mobile'                                                   ), // 2025.03.14 [IANA: DECE Mobile Video]
      ( Extension: '.uvp';         MimeType: 'video/vnd.dece.pd'                                                       ), // 2025.03.14 [IANA: DECE PD Video]
      ( Extension: '.uvs';         MimeType: 'video/vnd.dece.sd'                                                       ), // 2025.03.14 [IANA: DECE SD Video]
      ( Extension: '.uvu';         MimeType: 'video/vnd.uvvu.mp4'                                                      ), // 2025.03.14 [IANA: DECE MP4]
      ( Extension: '.uvv';         MimeType: 'video/vnd.dece.video'                                                    ), // 2025.03.14 [IANA: DECE Video]
      ( Extension: '.vcd';         MimeType: 'application/x-cdlink'                                                    ), // 2025.03.14 [Wikipedia: Video CD]
      ( Extension: '.vcf';         MimeType: 'text/x-vcard'                                                            ), // 2025.03.14 [Wikipedia: vCard]
      ( Extension: '.vcg';         MimeType: 'application/vnd.groove-vcard'                                            ), // 2025.03.14 [IANA: Groove]
      ( Extension: '.vcs';         MimeType: 'text/x-vcalendar'                                                        ), // 2025.03.14 [Wikipedia: vCalendar]
      ( Extension: '.vcx';         MimeType: 'application/vnd.vcx'                                                     ), // 2025.03.14 [IANA: VirtualCatalog]
      ( Extension: '.vis';         MimeType: 'application/vnd.visionary'                                               ), // 2025.03.14 [IANA: Visionary]
      ( Extension: '.viv';         MimeType: 'video/vnd.vivo'                                                          ), // 2025.03.14 [IANA: Vivo]
      ( Extension: '.vor';         MimeType: 'application/vnd.stardivision.writer'                                     ), // Indy 10.6.3.2
      ( Extension: '.vsd';         MimeType: 'application/vnd.visio'                                                   ), // 2025.03.14 [IANA: Visio]
      ( Extension: '.vsdx';        MimeType: 'application/vnd.visio2013'                                               ), // 2025.03.14 [IANA: Visio]
      ( Extension: '.vsf';         MimeType: 'application/vnd.vsf'                                                     ), // 2025.03.14 [IANA: Viewport+]
      ( Extension: '.vsl';         MimeType: 'application/x-cnet-vsl'                                                  ), // Indy 10.6.3.2
      ( Extension: '.vtu';         MimeType: 'model/vnd.vtu'                                                           ), // 2025.03.14 [IANA: VTU]
      ( Extension: '.vxml';        MimeType: 'application/voicexml+xml'                                                ), // 2025.03.14 [RFC 4267]
      ( Extension: '.wad';         MimeType: 'application/x-doom'                                                      ), // 2025.03.14 [Wikipedia: Doom WAD]
      ( Extension: '.wav';         MimeType: 'audio/x-wav'                                                             ), // 2025.03.14 [Wikipedia: WAV]
      ( Extension: '.wax';         MimeType: 'audio/x-ms-wax'                                                          ), // 2025.03.14 [Windows Media Metafiles]
      ( Extension: '.wb1';         MimeType: 'application/x-quattropro'                                                ), // Indy 10.6.3.2
      ( Extension: '.wb2';         MimeType: 'application/x-quattropro'                                                ), // Indy 10.6.3.2
      ( Extension: '.wb3';         MimeType: 'application/x-quattropro'                                                ), // Indy 10.6.3.2
      ( Extension: '.wbmp';        MimeType: 'image/vnd.wap.wbmp'                                                      ), // 2025.03.14 [IANA: WBMP]
      ( Extension: '.wbs';         MimeType: 'application/vnd.criticaltools.wbs+xml'                                   ), // 2025.03.14 [IANA: Critical Tools]
      ( Extension: '.wbxml';       MimeType: 'application/vnd.wap.wbxml'                                               ), // 2025.03.14 [IANA: WBXML]
      ( Extension: '.wcm';         MimeType: 'application/vnd.ms-works'                                                ), // Indy 10.6.3.2
      ( Extension: '.wdb';         MimeType: 'application/vnd.ms-works'                                                ), // Indy 10.6.3.2
      ( Extension: '.weba';        MimeType: 'audio/webm'                                                              ), // 2025.03.14 [WebM Project]
      ( Extension: '.webm';        MimeType: 'video/webm'                                                              ), // 2025.03.14 [WebM Project]
      ( Extension: '.webp';        MimeType: 'image/webp'                                                              ), // 2025.03.14 [Wikipedia: WebP]
      ( Extension: '.wg';          MimeType: 'application/vnd.pmi.widget'                                              ), // 2025.03.14 [IANA: Qualcomm's Plaza Mobile Internet]
      ( Extension: '.wgt';         MimeType: 'application/widget'                                                      ), // 2025.03.14 [W3C Widget Packaging and XML Configuration]
      ( Extension: '.wks';         MimeType: 'application/vnd.ms-works'                                                ), // Indy 10.6.3.2
      ( Extension: '.wm';          MimeType: 'video/x-ms-wm'                                                           ), // 2025.03.14 [Wikipedia: Advanced Systems Format (ASF)]
      ( Extension: '.wma';         MimeType: 'audio/x-ms-wma'                                                          ), // 2025.03.14 [Wikipedia: Windows Media Audio]
      ( Extension: '.wmd';         MimeType: 'application/x-ms-wmd'                                                    ), // 2025.03.14 [Wikipedia: Windows Media Player]
      ( Extension: '.wmf';         MimeType: 'application/x-msmetafile'                                                ), // 2025.03.14 [Wikipedia: Windows Metafile]
      ( Extension: '.wml';         MimeType: 'text/vnd.wap.wml'                                                        ), // 2025.03.14 [Wikipedia: WML]
      ( Extension: '.wmlc';        MimeType: 'application/vnd.wap.wmlc'                                                ), // 2025.03.14 [IANA: WMLC]
      ( Extension: '.wmls';        MimeType: 'text/vnd.wap.wmlscript'                                                  ), // 2025.03.14 [Wikipedia: WMLScript]
      ( Extension: '.wmlsc';       MimeType: 'application/vnd.wap.wmlscriptc'                                          ), // 2025.03.14 [IANA: WMLScript]
      ( Extension: '.wmp';         MimeType: 'video/x-ms-wmp'                                                          ), // Indy 10.6.3.2
      ( Extension: '.wms';         MimeType: 'application/x-ms-wms'                                                    ), // Indy 10.6.3.2
      ( Extension: '.wmv';         MimeType: 'video/x-ms-wmv'                                                          ), // 2025.03.14 [Wikipedia: Advanced Systems Format (ASF)]
      ( Extension: '.wmx';         MimeType: 'video/x-ms-wmx'                                                          ), // 2025.03.14 [Wikipedia: Advanced Systems Format (ASF)]
      ( Extension: '.wmz';         MimeType: 'application/x-ms-wmz'                                                    ), // 2025.03.14 [Wikipedia: Windows Media Player]
      ( Extension: '.woff';        MimeType: 'application/x-font-woff'                                                 ), // 2025.03.14 [Wikipedia: Web Open Font Format]
      ( Extension: '.wp5';         MimeType: 'application/wordperfect5.1'                                              ), // Indy 10.6.3.2
      ( Extension: '.wpd';         MimeType: 'application/wordperfect'                                                 ), // Indy 10.6.3.2
      ( Extension: '.wpd';         MimeType: 'application/vnd.wordperfect'                                             ), // 2025.03.14 [IANA: Wordperfect]
      ( Extension: '.wpl';         MimeType: 'application/vnd.ms-wpl'                                                  ), // 2025.03.14 [IANA: MS Windows Media Player Playlist]
      ( Extension: '.wps';         MimeType: 'application/vnd.ms-works'                                                ), // 2025.03.14 [IANA: MS Works]
      ( Extension: '.wqd';         MimeType: 'application/vnd.wqd'                                                     ), // 2025.03.14 [IANA: SundaHus WQ]
      ( Extension: '.wri';         MimeType: 'application/x-mswrite'                                                   ), // 2025.03.14 [Wikipedia: Wordpad]
      ( Extension: '.wrl';         MimeType: 'model/vrml'                                                              ), // 2025.03.14 [Wikipedia: VRML]
      ( Extension: '.wsc';         MimeType: 'text/scriptlet'                                                          ), // Indy 10.6.3.2
      ( Extension: '.wsdl';        MimeType: 'application/wsdl+xml'                                                    ), // 2025.03.14 [W3C Web Service Description Language]
      ( Extension: '.wspolicy';    MimeType: 'application/wspolicy+xml'                                                ), // 2025.03.14 [W3C Web Services Policy]
      ( Extension: '.wtb';         MimeType: 'application/vnd.webturbo'                                                ), // 2025.03.14 [IANA: WebTurbo]
      ( Extension: '.wvx';         MimeType: 'video/x-ms-wvx'                                                          ), // 2025.03.14 [Wikipedia: Advanced Systems Format (ASF)]
      ( Extension: '.x3d';         MimeType: 'application/vnd.hzn-3d-crossword'                                        ), // 2025.03.14 [IANA: 3D Crossword Plugin]
      ( Extension: '.xap';         MimeType: 'application/x-silverlight-app'                                           ), // 2025.03.14 [Wikipedia: Silverlight]
      ( Extension: '.xar';         MimeType: 'application/vnd.xara'                                                    ), // 2025.03.14 [IANA: CorelXARA]
      ( Extension: '.xbap';        MimeType: 'application/x-ms-xbap'                                                   ), // 2025.03.14 [Wikipedia: XAML Browser]
      ( Extension: '.xbd';         MimeType: 'application/vnd.fujixerox.docuworks.binder'                              ), // 2025.03.14 [IANA: Docuworks Binder]
      ( Extension: '.xbm';         MimeType: 'image/xbm'                                                               ), // Indy 10.6.3.2
      ( Extension: '.xbm';         MimeType: 'image/x-xbitmap'                                                         ), // 2025.03.14 [Wikipedia: X BitMap]
      ( Extension: '.xcf';         MimeType: 'image/x-xcf'                                                             ), // 2025.11.22 GIMP native image format
      ( Extension: '.xdf';         MimeType: 'application/xcap-diff+xml'                                               ), // 2025.03.14 [Wikipedia: XCAP]
      ( Extension: '.xdm';         MimeType: 'application/vnd.syncml.dm+xml'                                           ), // 2025.03.14 [IANA: SyncML]
      ( Extension: '.xdp';         MimeType: 'application/vnd.adobe.xdp+xml'                                           ), // 2025.03.14 [Wikipedia: XML Data Package]
      ( Extension: '.xdssc';       MimeType: 'application/dssc+xml'                                                    ), // 2025.03.14 [RFC 5698]
      ( Extension: '.xdw';         MimeType: 'application/vnd.fujixerox.docuworks'                                     ), // 2025.03.14 [IANA: Docuworks]
      ( Extension: '.xenc';        MimeType: 'application/xenc+xml'                                                    ), // 2025.03.14 [W3C XML Encryption Syntax and Processing]
      ( Extension: '.xer';         MimeType: 'application/patch-ops-error+xml'                                         ), // 2025.03.14 [RFC 5261]
      ( Extension: '.xfdf';        MimeType: 'application/vnd.adobe.xfdf'                                              ), // 2025.03.14 [Wikipedia: XML Portable Document Format]
      ( Extension: '.xfdl';        MimeType: 'application/vnd.xfdl'                                                    ), // 2025.03.14 [IANA: Extensible Forms Description Language]
      ( Extension: '.xht';         MimeType: 'application/xhtml+xml'                                                   ), // Indy 10.6.3.2
      ( Extension: '.xhtml';       MimeType: 'application/xhtml+xml'                                                   ), // 2025.03.14 [W3C XHTML]
      ( Extension: '.xif';         MimeType: 'image/vnd.xiff'                                                          ), // 2025.03.14 [IANA: XIFF]
      ( Extension: '.xlam';        MimeType: 'application/vnd.ms-excel.addin.macroenabled.12'                          ), // 2025.03.14 [IANA: MS Excel]
      ( Extension: '.xlb';         MimeType: 'application/x-msexcel'                                                   ), // Indy 10.6.3.2
      ( Extension: '.xls';         MimeType: 'application/x-msexcel'                                                   ), // Indy 10.6.3.2
      ( Extension: '.xls';         MimeType: 'application/vnd.ms-excel'                                                ), // 2025.03.14 [IANA: MS Excel]
      ( Extension: '.xlsb';        MimeType: 'application/vnd.ms-excel.sheet.binary.macroenabled.12'                   ), // 2025.03.14 [IANA: MS Excel]
      ( Extension: '.xlsm';        MimeType: 'application/vnd.ms-excel.sheet.macroenabled.12'                          ), // 2025.03.14 [IANA: MS Excel]
      ( Extension: '.xlsx';        MimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'       ), // 2025.03.14 [IANA: OOXML - Spreadsheet]
      ( Extension: '.xltm';        MimeType: 'application/vnd.ms-excel.template.macroenabled.12'                       ), // 2025.03.14 [IANA: MS Excel]
      ( Extension: '.xltx';        MimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template'    ), // 2025.03.14 [IANA: OOXML - Spreadsheet Template]
      ( Extension: '.xml';         MimeType: 'text/xml'                                                                ), // Indy 10.6.3.2
      ( Extension: '.xml';         MimeType: 'application/xml'                                                         ), // 2025.03.14 [W3C XML]
      ( Extension: '.xo';          MimeType: 'application/vnd.olpc-sugar'                                              ), // 2025.03.14 [IANA: Sugar Linux App Bundle]
      ( Extension: '.xop';         MimeType: 'application/xop+xml'                                                     ), // 2025.03.14 [W3C XOP]
      ( Extension: '.xpi';         MimeType: 'application/x-xpinstall'                                                 ), // 2025.03.14 [Wikipedia: XPI]
      ( Extension: '.xpm';         MimeType: 'image/x-xpixmap'                                                         ), // 2025.03.14 [Wikipedia: X PixMap]
      ( Extension: '.xpr';         MimeType: 'application/vnd.is-xpr'                                                  ), // 2025.03.14 [IANA: Express by Infoseek]
      ( Extension: '.xps';         MimeType: 'application/vnd.ms-xpsdocument'                                          ), // 2025.03.14 [IANA: MS XML Paper Specification]
      ( Extension: '.xpw';         MimeType: 'application/vnd.intercon.formnet'                                        ), // 2025.03.14 [IANA: Intercon FormNet]
      ( Extension: '.xsd';         MimeType: 'application/vnd.sun.xml.draw'                                            ), // Indy 10.6.3.2
      ( Extension: '.xslt';        MimeType: 'application/xslt+xml'                                                    ), // 2025.03.14 [W3C XSLT]
      ( Extension: '.xsm';         MimeType: 'application/vnd.syncml+xml'                                              ), // 2025.03.14 [IANA: SyncML]
      ( Extension: '.xspf';        MimeType: 'application/xspf+xml'                                                    ), // 2025.03.14 [XML Shareable Playlist Format]
      ( Extension: '.xul';         MimeType: 'application/vnd.mozilla.xul+xml'                                         ), // 2025.03.14 [IANA: XUL]
      ( Extension: '.xwd';         MimeType: 'image/x-xwindowdump'                                                     ), // 2025.03.14 [Wikipedia: X Window Dump]
      ( Extension: '.xyz';         MimeType: 'chemical/x-xyz'                                                          ), // 2025.03.14 [Wikipedia: XYZ File Format]

      ( Extension: '.yaml';        MimeType: 'text/yaml'                                                               ), // 2025.03.14 [YAML: YAML Ain't Markup Language]
      ( Extension: '.yang';        MimeType: 'application/yang'                                                        ), // 2025.03.14 [Wikipedia: YANG]
      ( Extension: '.yin';         MimeType: 'application/yin+xml'                                                     ), // 2025.03.14 [Wikipedia: YANG]
      ( Extension: '.ymp';         MimeType: 'text/x-suse-ymp'                                                         ), // 2025.11.22 [Gemini AI] (OpenSUSE YaST Meta Package)
      ( Extension: '.ysc';         MimeType: 'application/x-ysl-config'                                                ), // 2025.11.22 [Gemini AI]
      ( Extension: '.ytc';         MimeType: 'application/vnd.youtube.ytc'                                             ), // 2025.11.22 [Gemini AI]

      ( Extension: '.z';           MimeType: 'application/x-bzip'                                                      ), // Indy 10.6.3.2
      ( Extension: '.z';           MimeType: 'application/x-compress'                                                  ), // Indy 10.6.3.2
      ( Extension: '.z1';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z2';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z3';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z4';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z5';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z6';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z7';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.z8';          MimeType: 'application/x-zmachine'                                                  ), // 2025.11.22 [Gemini AI]
      ( Extension: '.zaz';         MimeType: 'application/vnd.zzazz.deck+xml'                                          ), // 2025.03.14 [IANA: Zzazz]
      ( Extension: '.zif';         MimeType: 'application/vnd.zul.zil'                                                 ), // 2025.11.22 [Gemini AI]
      ( Extension: '.zip';         MimeType: 'application/zip'                                                         ), // 2025.03.14 [Wikipedia: Zip]
      ( Extension: '.zip';         MimeType: 'application/x-zip-compressed'                                            ), // Indy 10.6.3.2
      ( Extension: '.zir';         MimeType: 'application/vnd.zul'                                                     ), // 2025.03.14 [IANA: Z.U.L.]
      ( Extension: '.zmm';         MimeType: 'application/vnd.handheld-entertainment+xml'                              ), // 2025.03.14 [IANA: ZVUE Media Manager]
      ( Extension: '.zoo';         MimeType: 'application/x-zoo'                                                       ), // Indy 10.6.3.2
      ( Extension: '.zpk';         MimeType: 'application/x-zpk'                                                       )  // 2025.11.22 [Gemini AI]


